### ISSUE TITLE
Sometimes object release fails

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#104]
Error reported:

```
Error: Node does not have a parent. Node uri: https://objecthub.io java.lang.RuntimeException: Node does not have a parent. Node uri: https://objecthub.io

Unknown.at Z4b(Unknown Source)

Unknown.at Object.dSb(Unknown Source)

Unknown.at Object.jSb(Unknown Source)

Unknown.at Object.mSb(Unknown Source)

Unknown.at FMd(Unknown Source)

Unknown.at WJe(Unknown Source)

Unknown.at Object.yue [as aj](Unknown Source)

Unknown.at Object.eval(Unknown Source)

Unknown.at b4b(Unknown Source)

-end of stack trace
Stacktrace:
Unknown.at Z4b(Unknown Source)

Unknown.at Object.dSb(Unknown Source)

Unknown.at Object.jSb(Unknown Source)

Unknown.at Object.mSb(Unknown Source)

Unknown.at FMd(Unknown Source)

Unknown.at WJe(Unknown Source)

Unknown.at Object.yue [as aj](Unknown Source)

Unknown.at Object.eval(Unknown Source)

Unknown.at b4b(Unknown Source)

-end of stack trace
Object.callback.onFailure (/var/task/index.js:172:230)
cb (/var/task/index.js:181:14)
Object.eval [as b] (line 36:13)
INe (eval at  (/var/task/index.js:21:100), :3245:23)
Object.cOe [as O] (eval at  (/var/task/index.js:21:100), :9541:362235)
Object.Ore [as O] (eval at  (/var/task/index.js:21:100), :9541:326964)
Object.aTe [as $] (eval at  (/var/task/index.js:21:100), :9541:368449)
aMe (eval at  (/var/task/index.js:21:100), :8363:51)
Object.tTe [as $] (eval at  (/var/task/index.js:21:100), :9541:368932)
KSe (eval at  (/var/task/index.js:21:100), :8924:165)
```

Another error reported:

```
{"errorMessage":"[object Object]"}
baseJs.js:70 Exception reported: (Error) : [object Object]
baseJs.js:71 com.google.gwt.core.client.JavaScriptException: (Error) : [object Object]<br />
Error: [object Object]<br/>
    at Sv.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…eens/.n/Object/.n/About_and_Manage/.n/Release__MA_/app_js/baseJs.js:125:20)<br/>
    at l5 (0.js:1612:332)<br/>
    at CDa._.w (0.js:1615:402)<br/>
    at Ajc._.P (0.js:1411:350)<br/>
    at Bjc._.P (0.js:1410:439)<br/>
    at ypc._.P (0.js:1660:451)<br/>
    at yFa._.Ec (0.js:341:299)<br/>
    at $rb._.nh (0.js:973:14)<br/>
    at XMLHttpRequest.eval (0.js:1104:323)<br/>
    at XMLHttpRequest.eval (0.js:2365:243)<br/>
```

**Comment by objecthub-io** [comment]
Works for objects that are already deployed:

```
START RequestId: e9b36696-c266-11e6-8e36-03fa2e713eca Version: $LATEST
2016-12-15T01:36:38.716Z	e9b36696-c266-11e6-8e36-03fa2e713eca	trigger service
2016-12-15T01:36:39.617Z	e9b36696-c266-11e6-8e36-03fa2e713eca	perform release object
2016-12-15T01:36:40.172Z	e9b36696-c266-11e6-8e36-03fa2e713eca	object already created. release new version for https://objecthub.io/hub/repo/~objects/~test-2
2016-12-15T01:36:40.173Z	e9b36696-c266-11e6-8e36-03fa2e713eca	release new version https://objecthub.io/hub/repo/~objects/~test-2
2016-12-15T01:36:42.555Z	e9b36696-c266-11e6-8e36-03fa2e713eca	get user node: link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*1/it/.n/Random_Tests1/.n/Section_2/.n/R2", "xxx")
END RequestId: e9b36696-c266-11e6-8e36-03fa2e713eca
REPORT RequestId: e9b36696-c266-11e6-8e36-03fa2e713eca	Duration: 7616.32 ms	Billed Duration: 7700 ms 	Memory Size: 512 MB	Max Memory Used: 121 MB	
```

**Comment by objecthub-io** [comment]
Does not work for first release

```
-37a43cf29311	perform release object
2016-12-15T01:39:39.018Z	54a49123-c267-11e6-b921-37a43cf29311	create released object test-2
2016-12-15T01:39:39.711Z	54a49123-c267-11e6-b921-37a43cf29311	created object reference(https://objecthub.io/hub/repo/~objects/~test-2, )
2016-12-15T01:39:40.294Z	54a49123-c267-11e6-b921-37a43cf29311	releasing versions reference(https://objecthub.io/hub/repo/~objects/~test-2, )
2016-12-15T01:39:40.294Z	54a49123-c267-11e6-b921-37a43cf29311	release new version https://objecthub.io/hub/repo/~objects/~test-2
2016-12-15T01:39:42.753Z	54a49123-c267-11e6-b921-37a43cf29311	get user node: link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*1/it/.n/Random_Tests1/.n/Section_2/.n/R3", "")
2016-12-15T01:39:43.154Z	54a49123-c267-11e6-b921-37a43cf29311	link("https://objecthub.io/hub/users/main/~objecthub", "") false
2016-12-15T01:39:43.171Z	54a49123-c267-11e6-b921-37a43cf29311	has parent true link("https://objecthub.io/hub/users/main/~objecthub", "")
2016-12-15T01:39:43.312Z	54a49123-c267-11e6-b921-37a43cf29311	link("https://objecthub.io/hub/users/main", "") false
2016-12-15T01:39:43.313Z	54a49123-c267-11e6-b921-37a43cf29311	has parent true link("https://objecthub.io/hub/users/main", "")
2016-12-15T01:39:43.355Z	54a49123-c267-11e6-b921-37a43cf29311	link("https://objecthub.io/hub/users", "") false
2016-12-15T01:39:43.355Z	54a49123-c267-11e6-b921-37a43cf29311	has parent true link("https://objecthub.io/hub/users", "")
2016-12-15T01:39:43.572Z	54a49123-c267-11e6-b921-37a43cf29311	link("https://objecthub.io/hub", "") false
2016-12-15T01:39:43.572Z	54a49123-c267-11e6-b921-37a43cf29311	has parent true link("https://objecthub.io/hub", "")
2016-12-15T01:39:43.600Z	54a49123-c267-11e6-b921-37a43cf29311	link("https://objecthub.io", "") false
2016-12-15T01:39:43.600Z	54a49123-c267-11e6-b921-37a43cf29311	has parent false link("https://objecthub.io", "")
2016-12-15T01:39:43.613Z	54a49123-c267-11e6-b921-37a43cf29311	{"errorMessage":"Node does not have a parent. Node uri: https://objecthub.io java.lang.Run
```

**Comment by objecthub-io** [comment]
Fixed.
