### ISSUE TITLE
Uncaught QuotaExceededError: Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#108]
Sometimes something like the following error occurs:

```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ort/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Class_and_Attribute/.n/Sample' exceeded the quota.
    at Object.put (0.js:570:356)
    at fA (0.js:1599:485)
    at pjc (0.js:1389:114)
    at mjc._.Xd (0.js:1389:210)
    at By (0.js:1348:481)
    at ljc._.F (0.js:1388:169)
    at kic._.F (0.js:1366:422)
    at kic._.kh (0.js:970:188)
    at eval (0.js:970:124)
    at eval (0.js:2365:243)
```

**Comment by objecthub-io** [comment]
Fixed.
