### ISSUE TITLE
Error when updating variable list (child not registered)

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#13]
Steps
- Import new variables to a micro app 

Findings
- Sometimes an error occurs 'Cannot remove from parent'

```
om.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", "")].
  Parent app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]<br />
Error: Cannot remove from parent. Child container was not registered with parent.<br/>
  Child app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", "")].<br/>
  Parent app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]<br/>
    at Object.lib.unregisterChild (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…t/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:40:13)<br/>
    at Object.lib.unload (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…t/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:47:27)<br/>
    at eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…eb/.n/Components/.n/Variables/.n/Variable_List__MA_/app_js/baseJs.js:79:28)<br/>
    at callFunction (0.js:132552:3)<br/>
    at Object.apply_660 [as apply_1] (0.js:132656:5)<br/>
    at $apply_383 (0.js:128819:77)<br/>
    at Object.apply_655 [as apply_1] (0.js:128836:3)<br/>
    at Object.onSuccess_8 (0.js:18855:81)<br/>
    at Object.onSuccess_118 [as onSuccess_0] (0.js:131342:82)<br/>
    at Object.onSuccess_101 [as onSuccess_0] (0.js:117945:79)<br/>
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
Unknown.$fillInStackTrace(Throwable.java:72)<br/>
Unknown.$$init_1138(Throwable.java:46)<br/>
Unknown.Throwable_0(Throwable.java:49)<br/>
Unknown.Exception_0(Exception.java:25)<br/>
Unknown.RuntimeException_0(RuntimeException.java:25)<br/>
Unknown.JavaScriptException_1(JavaScriptException.java:115)<br/>
Unknown.JavaScriptException_0(JavaScriptException.java:107)<br/>
```

**Comment by mxro** [comment]
Sometimes this comes up as well when navigating away from a Folder that is being updated or closing a database list (e.g. in the browser) while it is being reloaded

**Comment by objecthub-io** [comment]
Tried fixing by clearing items when micro app is unloaded - to monitor if it still occurs.

**Comment by mxro** [comment]
This comes up as well when changing the type of a node in the data editor:

```


Exception Message: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Element_Value_Link__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Multi_Type_Input__MA_", "")]
com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Element_Value_Link__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Multi_Type_Input__MA_", "")]
Error: Cannot remove from parent. Child container was not registered with parent.
Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Element_Value_Link__MA_", "")].
Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Multi_Type_Input__MA_", "")]
at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:40:13)
at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:47:27)
at Object.priv.unloadPrevious (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Multi_Type_Input__MA_/app_js/baseJs.js:113:17)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Multi_Type_Input__MA_/app_js/baseJs.js:158:14)
at callFunction (0.js:134475:3)
at Object.apply_692 [as apply_1] (0.js:134579:5)
at $apply_403 (0.js:130619:76)
at Object.apply_686 [as apply_1] (0.js:130636:3)
at Object.onSuccess_8 (0.js:19538:81)
at Object.onSuccess_118 [as onSuccess_0] (0.js:133265:82)
Unknown.$collect(JsArrayString.java:42)
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)
Unknown.fillInStackTrace(StackTraceCreator.java:508)
Unknown.$fillInStackTrace(Throwable.java:72)
Unknown.$$init_1187(Throwable.java:46)
Unknown.Throwable_0(Throwable.java:49)
Unknown.Exception_0(Exception.java:25)
Unknown.RuntimeException_0(RuntimeException.java:25)
Unknown.JavaScriptException_1(JavaScriptException.java:115)
Unknown.JavaScriptException_0(JavaScriptException.java:107)
Unknown.caught_0(Exceptions.java:29)
Unknown.callFunction(FnJs.java:115)
Unknown.apply_692(FnJs.java:80)

```

**Comment by objecthub-io** [comment]
Does not seem to appear anymore.
