### ISSUE TITLE
Usage Display Service sometimes fails

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#135]
Error reported:

```
com.google.gwt.core.client.JavaScriptException: (Error) : RequestId: fabc1e5e-f0b8-11e6-aa57-bb8c47359bf0 Process exited before completing request
Error: RequestId: fabc1e5e-f0b8-11e6-aa57-bb8c47359bf0 Process exited before completing request
at vw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Header/.n/Usage_Details_Display/app_js/baseJs.js:48:16)
at h5 (0.js:1640:332)
at mEa._.w (0.js:1643:402)
at lmc._.P (0.js:1432:350)
at mmc._.P (0.js:1431:439)
at Gsc._.P (0.js:1688:451)
at gGa._.Lc (0.js:353:299)
at mvb._.sh (0.js:999:14)
at XMLHttpRequest.eval (0.js:1130:323)
at XMLHttpRequest.eval (0.js:2402:243)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Header/.n/Usage_Details_Display/app_js/baseJs.js@16)
```

**Comment by objecthub-io** [comment]
Does not seem to happen anymore (after frequent server updates fixed)
