### ISSUE TITLE
Database Cannot be Accessed From Code

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#142]
# Steps

- Create a Database Object in a Folder
- DO NOT open the Database Object
- Drag and Drop Database Object onto a Micro Service
- Access Database from Micro Service

# Findings

The following error occurs:

```
Error: Error during service initialization: Undefined: Link cannot be resolved. No node defined at address: [path/~d] java.lang.Exception: Undefined: Link cannot be resolved. No node defined at address: [path/~d]
Unknown.at m9b(Unknown Source)
Unknown.at Object.sWb(Unknown Source)
Unknown.at Object.yWb(Unknown Source)
Unknown.at QSe(Unknown Source)
Unknown.at QSe(Unknown Source)
```

Note: after opening the database object it works.

**Comment by objecthub-io** [comment]
Fixed, since now database is opened right after it is created.
