### ISSUE TITLE
Error while loading Read Only Micro App

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#148]
Exception reported

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'getAuthorization' of undefined
TypeError: Cannot read property 'getAuthorization' of undefined
at zw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/app_js/baseJs.js:64:27)
at h5 (0.js:1639:332)
at Pqc._.w (0.js:1595:319)
at rA._.P (0.js:436:141)
at tTb._.P (0.js:1629:500)
at xmc._.P (0.js:1428:483)
at Tsc._.P (0.js:1687:451)
at tTb._.P (0.js:1629:500)
at xmc._.P (0.js:1428:483)
at Tsc._.P (0.js:1687:451)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/app_js/baseJs.js@27)
Unknown.h5(0.js@332)
Unknown._.w(0.js@319)
Unknown._.P(0.js@141)
Unknown._.P(0.js@500)
Unknown._.P(0.js@483)
Unknown._.P(0.js@451)
Unknown._.P(0.js@500)
Unknown._.P(0.js@483)
Unknown._.P(0.js@451)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
