### ISSUE TITLE
Error on Usage Page: 'Cannot read property 'getAuthorization' of undefined'

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#150]
When opening the public page for a user (without being logged in with another user), the following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'getAuthorization' of undefined<br />
TypeError: Cannot read property 'getAuthorization' of undefined<br/>
    at zw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…b/.n/Components/.n/Lists/.n/List_From_Database__MA_/app_js/baseJs.js:41:45)<br/>
    at h5 (0.js:1634:332)<br/>
    at Mqc._.w (0.js:1590:319)<br/>
    at rA._.P (0.js:434:141)<br/>
    at qTb._.P (0.js:1624:500)<br/>
    at umc._.P (0.js:1423:483)<br/>
    at Qsc._.P (0.js:1682:451)<br/>
    at SSb._.ai (0.js:1144:420)<br/>
    at JJc._.F (0.js:2360:236)<br/>
    at xIc._.F (0.js:2328:190)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…_Web/.n/Components/.n/Lists/.n/List_From_Database__MA_/app_js/baseJs.js@45)<br/>
Unknown.h5(0.js@332)<br/>
Unknown._.w(0.js@319)<br/>
Unknown._.P(0.js@141)<br/>
Unknown._.P(0.js@500)<br/>
Unknown._.P(0.js@483)<br/>
Unknown._.P(0.js@451)<br/>
Unknown._.ai(0.js@420)<br/>
Unknown._.F(0.js@236)<br/>
Unknown._.F(0.js@190)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
