### ISSUE TITLE
Variables sometimes cannot be rendered. Error 'Collect_Object_Dependencies.perform is not a function'

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#157]
Error reported:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Collect_Object_Dependencies.perform is not a function
TypeError: Collect_Object_Dependencies.perform is not a function
at Object.priv.installHooks (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/app_js/baseJs.js:25:33)
at zw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_/app_js/baseJs.js:267:14)
```

**Comment by mxro** [comment]
Maybe caused by this being still loaded.

e.g. HTML tab starts loading the library - but then JS tab opens it before it is properly initialised?

**Comment by objecthub-io** [comment]
Maybe a related error:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Select_Custom_Domain.onStepCompleted is not a function
TypeError: Select_Custom_Domain.onStepCompleted is not a function
at Object.app.init (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Domain/.n/Domain_Selection/app_js/baseJs.js:465:26)
at Object.priv.callInit (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:9)
at yw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:56:19)
at p5 (0.js:1642:332)
at pqc._.G (0.js:1580:70)
at rlc (0.js:1380:230)
at slc._.P (0.js:1381:154)
at rqc._.Gb (0.js:1580:267)
at btc._.Nl (0.js:1673:333)
at btc.Iv.0.2 (0.js:1674:362)
Unknown.app.init(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Domain/.n/Domain_Selection/app_js/baseJs.js@26)
Unknown.priv.callInit(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@9)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@19)
Unknown.p5(0.js@332)
Unknown._.G(0.js@70)
Unknown.rlc(0.js@230)
Unknown._.P(0.js@154)
Unknown._.Gb(0.js@267)
Unknown._.Nl(0.js@333)
Unknown.Iv.0.2(0.js@362)
```

**Comment by mxro** [comment]
Another error:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Collect_Object_Dependencies_for_List.perform is not a function<br />
TypeError: Collect_Object_Dependencies_for_List.perform is not a function<br/>
    at Fw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…b_Web/.n/Tools/.n/Bundle_Assembly/.n/Process_Micro_Library/baseJs.js:96:46)<br/>
    at o5 (0.js:1659:236)<br/>
    at LEa._.w (0.js:1661:438)<br/>
    at soc._.P (0.js:1447:409)<br/>
    at toc._.P (0.js:1446:483)<br/>
    at Ruc._.P (0.js:1706:451)<br/>
    at ns._.P (0.js:1705:270)<br/>
    at RD (0.js:1390:84)<br/>
    at wmc._.P (0.js:1390:195)<br/>
    at Mrc._.Gb (0.js:1597:267)<br/>
    at vuc._.Nl (0.js:1689:333)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…tHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Process_Micro_Library/baseJs.js@46)<br/>
Unknown.o5(0.js@236)<br/>
Unknown._.w(0.js@438)<br/>
Unknown._.P(0.js@409)<br/>
Unknown._.P(0.js@483)<br/>
Unknown._.P(0.js@451)<br/>
Unknown._.P(0.js@270)<br/>
Unknown.RD(0.js@84)<br/>
Unknown._.P(0.js@195)<br/>
Unknown._.Gb(0.js@267)<br/>
Unknown._.Nl(0.js@333)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Another error:

```
om.google.gwt.core.client.JavaScriptException: (TypeError) : Process_Micro_Library.process is not a function<br />
TypeError: Process_Micro_Library.process is not a function<br/>
    at Fw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…undle_Assembly/.n/Operation_-_Collect_Object_Dependencies1/baseJs.js:36:35)<br/>
    at o5 (0.js:1659:236)<br/>
    at mqc._.w (0.js:1616:284)<br/>
    at AA._.P (0.js:443:141)<br/>
    at tVb._.P (0.js:1649:500)<br/>
    at toc._.P (0.js:1446:483)<br/>
    at Ruc._.P (0.js:1706:451)<br/>
    at X_b._.w (0.js:1276:200)<br/>
    at Suc._.P (0.js:1704:411)<br/>
    at tVb._.P (0.js:1649:500)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…n/Bundle_Assembly/.n/Operation_-_Collect_Object_Dependencies1/baseJs.js@35)<br/>
Unknown.o5(0.js@236)<br/>
Unknown._.w(0.js@284)<br/>
Unknown._.P(0.js@141)<br/>
Unknown._.P(0.js@500)<br/>
Unknown._.P(0.js@483)<br/>
Unknown._.P(0.js@451)<br/>
Unknown._.w(0.js@200)<br/>
Unknown._.P(0.js@411)<br/>
Unknown._.P(0.js@500)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed. Probably caused by faulty compilations of Micro Libraries (this was fixed a while ago). Recompiling the libraries fixed the issue.

**Comment by objecthub-io** [comment]
This error is coming up again:

```
Exception reported: (TypeError) : Process_Micro_Library.process is not a function
hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/Objec…Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:88 com.google.gwt.core.client.JavaScriptException: (TypeError) : Process_Micro_Library.process is not a function<br />
TypeError: Process_Micro_Library.process is not a function<br/>
    at Fw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…undle_Assembly/.n/Operation_-_Collect_Object_Dependencies1/baseJs.js:34:35)<br/>
    at o5 (0.js:1659:236)<br/>
    at mqc._.w (0.js:1616:284)<br/>
    at AA._.P (0.js:443:141)<br/>
    at tVb._.P (0.js:1649:500)<br/>
    at toc._.P (0.js:1446:483)<br/>
    at Ruc._.P (0.js:1706:451)<br/>
    at X_b._.w (0.js:1276:200)<br/>
    at Suc._.P (0.js:1704:411)<br/>
    at tVb._.P (0.js:1649:500)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…n/Bundle_Assembly/.n/Operation_-_Collect_Object_Dependencies1/baseJs.js@35)<br/>
Unknown.o5(0.js@236)<br/>
Unknown._.w(0.js@284)<br/>
Unknown._.P(0.js@141)<br/>
Unknown._.P(0.js@500)<br/>
Unknown._.P(0.js@483)<br/>
Unknown._.P(0.js@451)<br/>
Unknown._.w(0.js@200)<br/>
Unknown._.P(0.js@411)<br/>
Unknown._.P(0.js@500)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Error reported:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Process_Micro_Library.process is not a function<br />
TypeError: Process_Micro_Library.process is not a function<br/>
    at Object.lib.process (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Process_Micro_App/baseJs.js:9:27)<br/>
    at Fw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…undle_Assembly/.n/Operation_-_Collect_Object_Dependencies1/baseJs.js:41:31)<br/>
    at o5 (0.js:1658:332)<br/>
    at sqc._.w (0.js:1615:284)<br/>
    at HA._.P (0.js:442:141)<br/>
    at wVb._.P (0.js:1648:500)<br/>
    at Doc._.P (0.js:1445:483)<br/>
    at Xuc._.P (0.js:1706:451)<br/>
    at Z_b._.w (0.js:1275:200)<br/>
    at Yuc._.P (0.js:1704:411)<br/>
Unknown.lib.process(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…bjectHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Process_Micro_App/baseJs.js@27)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…n/Bundle_Assembly/.n/Operation_-_Collect_Object_Dependencies1/baseJs.js@31)<br/>
Unknown.o5(0.js@332)<br/>
Unknown._.w(0.js@284)<br/>
Unknown._.P(0.js@141)<br/>
Unknown._.P(0.js@500)<br/>
Unknown._.P(0.js@483)<br/>
Unknown._.P(0.js@451)<br/>
Unknown._.w(0.js@200)<br/>
Unknown._.P(0.js@411)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Interestingly, this does not seem to appear for users other than the objecthub user.

Maybe it has something to do with the resolution of secrets for this user?

**Comment by objecthub-io** [comment]
Yes, this was the reason. Session ReadOnly secret is not defined for user ObjectHub. So the access secret for the libraries needs to be loaded individually. 

This takes more time than using the session secret.

**Comment by objecthub-io** [comment]
No issue, see previous comments.
