### ISSUE TITLE
Preview does not load correctly if there is an embedded micro app

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#16]
Exception

```
(ReferenceError) : framework is not defined

com.google.gwt.core.client.JavaScriptException: (ReferenceError) : framework is not defined
ReferenceError: framework is not defined
at cmpl_getSecret (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/About_and_Manage/.n/Details/.n/Card_Preview/app_js.value.js:7:23)
at init (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/About_and_Manage/.n/Details/.n/Card_Preview/app_js.value.js:60:1)
at Object.window.Libraries.install (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:89:10)
at Object.priv.requireOne (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:112:29)
at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:120:21
```

**Comment by mxro** [comment]
Fixed, framework was not included in test environment compilation.
