### ISSUE TITLE
Error during login when session token not valid anymore

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#160]
# Steps

Open the browser with a cookie of the session token, for which the session token is expired.

# Findings

The following error occurs. The page does not load.

```
com.google.gwt.core.client.JavaScriptException: (ReferenceError) : Cookies is not defined<br />
ReferenceError: Cookies is not defined<br/>
    at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Hub_Web/.n/Screens/.n/User_Management/.n/Sign_In/.n/Sign_In/baseJs.js:14:9)<br/>
    at Gw._.w (0.js:1645:24)<br/>
    at Qsc._.$ (0.js:1667:212)<br/>
    at Au (0.js:1635:88)<br/>
    at lVb._.w (0.js:1189:414)<br/>
    at $mc._.O (0.js:1431:269)<br/>
    at anc._.O (0.js:1430:358)<br/>
    at ttc._.$ (0.js:1689:350)<br/>
    at Au (0.js:1635:88)<br/>
    at xtc._.$ (0.js:1690:383)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Screens/.n/User_Management/.n/Sign_In/.n/Sign_In/baseJs.js@9)<br/>
Unknown._.w(0.js@24)<br/>
Unknown._.$(0.js@212)<br/>
Unknown.Au(0.js@88)<br/>
Unknown._.w(0.js@414)<br/>
Unknown._.O(0.js@269)<br/>
Unknown._.O(0.js@358)<br/>
Unknown._.$(0.js@350)<br/>
Unknown.Au(0.js@88)<br/>
Unknown._.$(0.js@383)<br/>
-end of stack trace
```

# Workaround

Delete cookies, then load page again.

**Comment by stellardb** [comment]
Fixed.
