### ISSUE TITLE
Opening Micro Service on Explorer: Error `params.forceCompile is not a function`

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#176]
Error reported:

```
Uncaught TypeError: params.forceCompile is not a function
    at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…itors/.n/Micro_Service1/.n/Micro_Service_Test__MA_/app_js/baseJs.js:171:16)
    at Gw._.w (0.js:1645:24)
    at Tsc._._ (0.js:1667:411)
    at Py (0.js:1636:26)
    at Py (0.js:1636:83)
    at eu._._ (0.js:1636:269)
    at Hy (0.js:1637:284)
    at Au (0.js:1635:68)
    at XTb._.O (0.js:1632:448)
    at anc._.O (0.js:1430:358)
```

**Comment by stellardb** [comment]
Fixed. Removed preview from Micro Services for now.
