### ISSUE TITLE
Cannot move nodes in data editor

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#177]
When trying to move a node in the data editor (e.g. change position) the following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (Error) : Cannot move this node. It is owned by this object.<br />
Error: Cannot move this node. It is owned by this object.<br/>
    at Object.priv.performInsert (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.….n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js:227:16)<br/>
    at zw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.….n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js:381:14)<br/>
    at p5 (0.js:1643:332)<br/>
    at sqc._.G (0.js:1581:70)<br/>
    at tlc (0.js:1381:230)<br/>
    at ulc._.P (0.js:1382:154)<br/>
    at uqc._.Gb (0.js:1581:267)<br/>
    at etc._.Nl (0.js:1674:333)<br/>
    at etc.Jv.0.2 (0.js:1675:362)<br/>
    at Z9 (0.js:2395:239)<br/>
Unknown.priv.performInsert(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js@16)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js@14)<br/>
Unknown.p5(0.js@332)<br/>
Unknown._.G(0.js@70)<br/>
Unknown.tlc(0.js@230)<br/>
Unknown._.P(0.js@154)<br/>
Unknown._.Gb(0.js@267)<br/>
Unknown._.Nl(0.js@333)<br/>
Unknown.Jv.0.2(0.js@362)<br/>
Unknown.Z9(0.js@239)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
