### ISSUE TITLE
Date display does not work for data editor

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#181]
When creating a new node of the type date and then opening this node in the data editor, the following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'create' of undefined<br />
TypeError: Cannot read property 'create' of undefined<br/>
    at Dw.priv.initInput [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Components/.n/Value_Links/.n/Date_Input__MA_/app_js/baseJs.js:51:24)<br/>
    at p5 (0.js:1660:236)<br/>
    at Drc._.G (0.js:1598:70)<br/>
    at Emc (0.js:1396:230)<br/>
    at Fmc._.P (0.js:1397:154)<br/>
    at Frc._.Gb (0.js:1598:267)<br/>
    at ouc._.Nl (0.js:1690:333)<br/>
    at ouc.Nv.0.2 (0.js:1691:362)<br/>
    at Z9 (0.js:2417:253)<br/>
    at R (0.js:2420:393)<br/>
Unknown.priv.initInput(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ub_Web/.n/Components/.n/Value_Links/.n/Date_Input__MA_/app_js/baseJs.js@24)<br/>
Unknown.p5(0.js@236)<br/>
Unknown._.G(0.js@70)<br/>
Unknown.Emc(0.js@230)<br/>
Unknown._.P(0.js@154)<br/>
Unknown._.Gb(0.js@267)<br/>
Unknown._.Nl(0.js@333)<br/>
Unknown.Nv.0.2(0.js@362)<br/>
Unknown.Z9(0.js@253)<br/>
Unknown.R(0.js@393)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
