### ISSUE TITLE
When running a query which includes rows which undefined references, error occurs

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#182]
There is a foreign key reference to another node and this is not defined. The following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'uri' of null<br />
TypeError: Cannot read property 'uri' of null<br/>
    at Object.app.init (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Hub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_/app_js/baseJs.js:30:22)<br/>
    at Object.priv.callInit (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:9)<br/>
    at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ctHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:56:19)<br/>
    at p5 (0.js:1660:236)<br/>
    at Drc._.G (0.js:1598:70)<br/>
    at Emc (0.js:1396:230)<br/>
    at Fmc._.P (0.js:1397:154)<br/>
    at Frc._.Gb (0.js:1598:267)<br/>
    at ouc._.Nl (0.js:1690:333)<br/>
    at ouc.Nv.0.2 (0.js:1691:362)<br/>
Unknown.app.init(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_/app_js/baseJs.js@22)<br/>
Unknown.priv.callInit(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@9)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…bjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@19)<br/>
Unknown.p5(0.js@236)<br/>
Unknown._.G(0.js@70)<br/>
Unknown.Emc(0.js@230)<br/>
Unknown._.P(0.js@154)<br/>
Unknown._.Gb(0.js@267)<br/>
Unknown._.Nl(0.js@333)<br/>
Unknown.Nv.0.2(0.js@362)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Fixed.
