### ISSUE TITLE
Error in Database/Query tab after viewing empty table.

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#184]
In the Database Editor, when viewing a table with no results (editor shows `Empty result set received.`) and AFTERWARDS opening another table (with results), the following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_", class java.lang.String)].
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…jectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_", "")]<br />
Error: Cannot remove from parent. Child container was not registered with parent.<br/>
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_", class java.lang.String)].<br/>
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…jectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_", "")]<br/>
    at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:49:13)<br/>
    at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:56:27)<br/>
    at displayResult (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…on_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js/baseJs.js:162:29)<br/>
    at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…on_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js/baseJs.js:105:13)<br/>
    at p5 (0.js:1660:236)<br/>
    at FEa._.w (0.js:1662:438)<br/>
    at loc._.P (0.js:1448:409)<br/>
    at moc._.P (0.js:1447:483)<br/>
    at Kuc._.P (0.js:1707:451)<br/>
    at zJa._.F (0.js:420:213)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.lib.unregisterChild(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@13)<br/>
Unknown.lib.unload(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@27)<br/>
Unknown.displayResult(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…sition_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js/baseJs.js@29)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…sition_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js/baseJs.js@13)<br/>
Unknown.p5(0.js@236)<br/>
Unknown._.w(0.js@438)<br/>
Unknown._.P(0.js@409)<br/>
Unknown._.P(0.js@483)<br/>
Unknown._.P(0.js@451)<br/>
Unknown._.F(0.js@213)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Fixed.
