### ISSUE TITLE
Micro Pages do not render anymore

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#186]
# Steps

- Create a new Micro Page
- View in in the preview or in a new tab

# Findings

Opening the page 'hangs'. Nothing is displayed.

**Comment by stellardb** [comment]
Error reported on server:

```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:447)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:409)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:358)
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:2147)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:2117)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1299)
	at com.appjangle.rest.nodes.lambda.LambdaScriptExecutionService$1.apply(LambdaScriptExecutionService.java:187)
	at com.appjangle.rest.nodes.lambda.LambdaScriptExecutionService$1.apply(LambdaScriptExecutionService.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:225)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:142)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.appjangle.api.queries.Queries$6$1.apply(Queries.java:312)
	at com.appjangle.api.queries.Queries$6$1.apply(Queries.java:1)
	at io.nextweb.promise.utils.CallbackUtils$2.onSuccess(CallbackUtils.java:66)
	at io.nextweb.promise.DataPromiseImpl$1.onSuccess(DataPromiseImpl.java:72)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:142)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$2.thenDo(P_Entity_Select.java:315)
	at one.engine.nx.internal.operations.SelectNodesOperation$1.thenDo(SelectNodesOperation.java:83)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:68)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:258)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:1)
	at delight.async.flow.CallbackMap$1.onSuccess(CallbackMap.java:50)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$4.onSuccess(LoadAndSynchronizeOperation.java:284)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:233)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:166)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:278)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:166)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:54)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at one.engine.nx.internal.operations.SelectNodesOperation.performSelect(SelectNodesOperation.java:40)
	at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:33)
	at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.select.SelectChildrenWithQueryGrammar.and(SelectChildrenWithQueryGrammar.java:28)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1.apply(P_Entity_Select.java:301)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1.apply(P_Entity_Select.java:1)
	at io.nextweb.promise.utils.CallbackUtils$2.onSuccess(CallbackUtils.java:66)
	at com.ononedb.nextweb.OnedbNode.apply(OnedbNode.java:186)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5.apply(P_Entity_Select.java:272)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.apply(PromiseImpl.java:30)
	at io.nextweb.promise.DataPromiseImpl.apply(DataPromiseImpl.java:76)
	at com.ononedb.nextweb.OnedbNodeListQuery.apply(OnedbNodeListQuery.java:45)
	at com.appjangle.api.queries.Queries$6.apply(Queries.java:321)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.get(PromiseImpl.java:193)
	at io.nextweb.promise.DataPromiseImpl.get(DataPromiseImpl.java:33)
	at com.appjangle.rest.nodes.lambda.LambdaScriptExecutionService.process(LambdaScriptExecutionService.java:291)
	at com.appjangle.rest.nodes.internal.ProcessScript$5.apply(ProcessScript.java:279)
	at com.appjangle.rest.nodes.internal.ProcessScript$5.apply(ProcessScript.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:225)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:142)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$2.thenDo(P_Entity_Select.java:315)
	at one.engine.nx.internal.operations.SelectNodesOperation$1.thenDo(SelectNodesOperation.java:83)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1.onSuccess(LoadAndSynchronizeOperation.java:68)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:258)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$3.onSuccess(LoadAndSynchronizeOperation.java:1)
	at delight.async.flow.CallbackMap$1.onSuccess(CallbackMap.java:50)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$4.onSuccess(LoadAndSynchronizeOperation.java:284)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:233)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:166)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeChildren(LoadAndSynchronizeOperation.java:278)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.loadNodeAndChildren(LoadAndSynchronizeOperation.java:166)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:54)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation.execute(LoadAndSynchronizeOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.common.NodeGrammarWithCallbackData.execute(NodeGrammarWithCallbackData.java:15)
	at one.core.dsl.grammars.LoadGrammarAbstract.and(LoadGrammarAbstract.java:95)
	at one.engine.nx.internal.operations.SelectNodesOperation.performSelect(SelectNodesOperation.java:40)
	at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:33)
	at one.engine.nx.internal.operations.SelectNodesOperation.execute(SelectNodesOperation.java:1)
	at one.core.dsl.grammars.common.GrammarData.execute(GrammarData.java:35)
	at one.core.dsl.grammars.common.NodeGrammarData.execute(NodeGrammarData.java:23)
	at one.core.dsl.grammars.select.SelectChildrenWithQueryGrammar.and(SelectChildrenWithQueryGrammar.java:28)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1.apply(P_Entity_Select.java:301)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1.apply(P_Entity_Select.java:1)
	at io.nextweb.promise.utils.CallbackUtils$2.onSuccess(CallbackUtils.java:66)
	at com.ononedb.nextweb.OnedbNode.apply(OnedbNode.java:186)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5.apply(P_Entity_Select.java:272)
	at com.ononedb.nextweb.jre.OnedbJreFactory$1.apply(OnedbJreFactory.java:48)
	at delight.promise.internal.PromiseImpl.requestResult(PromiseImpl.java:88)
	at delight.promise.internal.PromiseImpl.get(PromiseImpl.java:193)
	at io.nextweb.promise.DataPromiseImpl.get(DataPromiseImpl.java:33)
	at com.ononedb.nextweb.OnedbNodeListQuery.get(OnedbNodeListQuery.java:134)
	at com.appjangle.rest.nodes.internal.ProcessScript.processScript(ProcessScript.java:285)
	at com.appjangle.rest.nodes.internal.ProcessScript.access$7(ProcessScript.java:267)
	at com.appjangle.rest.nodes.internal.ProcessScript$4.apply(ProcessScript.java:244)
	at com.appjangle.rest.nodes.internal.ProcessScript$4.apply(ProcessScript.java:1)
	at delight.promise.internal.PromiseImpl$3.onSuccess(PromiseImpl.java:225)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:142)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.appjangle.api.queries.Queries$3$1.apply(Queries.java:117)
	at com.appjangle.api.queries.Queries$3$1.apply(Queries.java:1)
	at io.nextweb.promise.utils.CallbackUtils$2.onSuccess(CallbackUtils.java:66)
	at io.nextweb.promise.DataPromiseImpl$1.onSuccess(DataPromiseImpl.java:72)
	at delight.promise.internal.PromiseImpl$1.onSuccess(PromiseImpl.java:142)
	at io.nextweb.promise.utils.CallbackUtils$9.onSuccess(CallbackUtils.java:204)
	at com.ononedb.nextweb.plugins.impl.P_Entity_Select$5$1$2.thenDo(P_Entity_Select.java:315)
	at one.engine.nx.internal.operations.SelectNodesOperation$1.thenDo(SelectNodesOperation.java:83)
	at one.engine.nx.internal.operations.LoadAndSynchronizeOperation$1$1.run(LoadAndSynchronizeOperation.java:87)
	at one.engine.nx.internal.CallbackSequencer$1.run(CallbackSequencer.java:43)
	at one.engine.nx.internal.ClientWrapper$5.process(ClientWrapper.java:200)
	at delight.scheduler.BetterAccessThreadImplementation.processItems(BetterAccessThreadImplementation.java:131)
	at delight.scheduler.BetterAccessThreadImplementation.run(BetterAccessThreadImplementation.java:118)
	at delight.scheduler.BetterAccessThreadImplementation$1.run(BetterAccessThreadImplementation.java:81)
	at delight.concurrency.jre.JavaExecutor$4.run(JavaExecutor.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mxro** [comment]
Problem seems to be caused by loading Render Page Micro Library.

And here specifically loading the Generate_Bundle dependency of this library.

**Comment by mxro** [comment]
Fixed.

Was caused by circular dependencies in creating bundle tooling.
