### ISSUE TITLE
Domain: Unlink Domain is not working

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#192]
Trying to unlink a domain, which was linked to the production version of a Micro App.

Error show:

```
com.google.gwt.core.client.JavaScriptException: (Error) : Unauthorized: No secret matching the supplied secret.
  Secret: [Token.UNSPECIFIED_TOKEN]
  Node [Nx.reference(https://u1.objecthub.io/objecthub/home/my/~*3/data/.n/Tests_5/.n/UM_10/.n/Frontend/.n/um10_on_objecthub_io)]
  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]<br />
Error: Unauthorized: No secret matching the supplied secret.<br/>
  Secret: [Token.UNSPECIFIED_TOKEN]<br/>
  Node [Nx.reference(https://u1.objecthub.io/objecthub/home/my/~*3/data/.n/Tests_5/.n/UM_10/.n/Frontend/.n/um10_on_objecthub_io)]<br/>
  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]<br/>
    at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Basic_Editors/.n/Domain/.n/Domain_Selection/app_js/baseJs.js:418:28)<br/>
    at o5 (0.js:1655:332)<br/>
    at OEa._.x (0.js:1658:481)<br/>
    at Eoc._.Q (0.js:1442:409)<br/>
    at Foc._.Q (0.js:1441:483)<br/>
    at Zuc._.Q (0.js:1703:452)<br/>
    at UGa._.x (0.js:348:275)<br/>
    at HGa._.x (0.js:348:437)<br/>
    at LGa._.Nc (0.js:353:412)<br/>
    at txb._.wh (0.js:1006:14)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Hub_Web/.n/Basic_Editors/.n/Domain/.n/Domain_Selection/app_js/baseJs.js@28)<br/>
Unknown.o5(0.js@332)<br/>
Unknown._.x(0.js@481)<br/>
Unknown._.Q(0.js@409)<br/>
Unknown._.Q(0.js@483)<br/>
Unknown._.Q(0.js@452)<br/>
Unknown._.x(0.js@275)<br/>
Unknown._.x(0.js@437)<br/>
Unknown._.Nc(0.js@412)<br/>
Unknown._.wh(0.js@14)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
