### ISSUE TITLE
Cannot deploy ObjectHub IDE bundle

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#197]
Because of problem with loading dependencies using 'objecthub' user (see #157).

Error reported:

```
Cannot deploy new version.Show more ...   
Hide
Exception Message: (TypeError) : Collect_Object_Dependencies_for_List.perform is not a function

com.google.gwt.core.client.JavaScriptException: (TypeError) : Collect_Object_Dependencies_for_List.perform is not a function
TypeError: Collect_Object_Dependencies_for_List.perform is not a function
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Process_CoffeeScript1/baseJs.js:21:46)
at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Shared_-_Process_Code/baseJs.js:124:13)
at p5 (0.js:1662:332)
at QEa._.x (0.js:1665:481)
at Soc._.Q (0.js:1448:409)
at Toc._.Q (0.js:1447:483)
at pvc._.Q (0.js:1710:452)
at ls._.Q (0.js:1709:271)
at WD (0.js:1390:317)
at Xmc._.Q (0.js:1390:428)
at gsc._.Hb (0.js:1600:267)
at Uuc._.Ol (0.js:1693:333)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Process_CoffeeScript1/baseJs.js@46)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Tools/.n/Bundle_Assembly/.n/Shared_-_Process_Code/baseJs.js@13)
Unknown.p5(0.js@332)
Unknown._.x(0.js@481)
Unknown._.Q(0.js@409)
Unknown._.Q(0.js@483)
Unknown._.Q(0.js@452)
Unknown._.Q(0.js@271)
Unknown.WD(0.js@317)
Unknown._.Q(0.js@428)
Unknown._.Hb(0.js@267)
Unknown._.Ol(0.js@333)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
