### ISSUE TITLE
Compilation of test environments does not work

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#198]
# Steps

- Create a new test environment for a Micro App
- Create a new parameter

# Findings

The following error occurs:

```
Exception Message: (TypeError) : state.importsLib.getSecretCode is not a function

com.google.gwt.core.client.JavaScriptException: (TypeError) : state.importsLib.getSecretCode is not a function
TypeError: state.importsLib.getSecretCode is not a function
at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Compile_Test_Environment.value.js:176:40)
at o5 (0.js:1659:332)
at Yrc._.H (0.js:1597:70)
at enc (0.js:1392:415)
at fnc._.Q (0.js:1393:269)
at $rc._.Hb (0.js:1597:267)
at Juc._.Ol (0.js:1690:333)
at Juc.Kuc.Nv.0.2 (0.js:1691:362)
at Z9 (0.js:2418:239)
at R (0.js:2421:393)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Compile_Test_Environment.value.js@40)
Unknown.o5(0.js@332)
Unknown._.H(0.js@70)
Unknown.enc(0.js@415)
Unknown._.Q(0.js@269)
Unknown._.Hb(0.js@267)
Unknown._.Ol(0.js@333)
Unknown.Kuc.Nv.0.2(0.js@362)
Unknown.Z9(0.js@239)
Unknown.R(0.js@393)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
