### ISSUE TITLE
Error when deleting parameter from test environment

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#199]
Error reported:

```
Exception reported: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…b_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Parameter__MA_", "")].
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Parameters__MA_", "")]
baseJs.js:88 com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…b_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Parameter__MA_", "")].
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Parameters__MA_", "")]<br />
Error: Cannot remove from parent. Child container was not registered with parent.<br/>
  Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…b_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Parameter__MA_", "")].<br/>
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…_Web/.n/Basic_Editors/.n/Micro_App/.n/Preview/Test_Data/.n/Parameters__MA_", "")]<br/>
    at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:49:13)<br/>
    at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:56:27)<br/>
    at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…n/Micro_App/.n/Preview/Test_Data/.n/Parameters__MA_/app_js/baseJs.js:96:22)<br/>
    at o5 (0.js:1659:332)<br/>
    at Yrc._.H (0.js:1597:70)<br/>
    at enc (0.js:1392:415)<br/>
    at fnc._.Q (0.js:1393:269)<br/>
    at $rc._.Hb (0.js:1597:267)<br/>
    at Juc._.Ol (0.js:1690:333)<br/>
    at Juc.Kuc.Nv.0.2 (0.js:1691:362)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.lib.unregisterChild(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@13)<br/>
Unknown.lib.unload(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@27)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…s/.n/Micro_App/.n/Preview/Test_Data/.n/Parameters__MA_/app_js/baseJs.js@22)<br/>
Unknown.o5(0.js@332)<br/>
Unknown._.H(0.js@70)<br/>
Unknown.enc(0.js@415)<br/>
Unknown._.Q(0.js@269)<br/>
Unknown._.Hb(0.js@267)<br/>
Unknown._.Ol(0.js@333)<br/>
Unknown.Kuc.Nv.0.2(0.js@362)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
