### ISSUE TITLE
Unlink Domain is not working

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#203]
When trying to unlink a domain that was previously linked with the Domain object, the following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (Error) : Specify parameter target.<br />
Error: Specify parameter target.<br/>
    at Dw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Basic_Editors/.n/Domain/.n/Domain_Selection/app_js/baseJs.js:418:28)<br/>
    at p5 (0.js:1662:332)<br/>
    at QEa._.x (0.js:1665:481)<br/>
    at Woc._.Q (0.js:1448:409)<br/>
    at Xoc._.Q (0.js:1447:483)<br/>
    at pvc._.Q (0.js:1710:452)<br/>
    at XGa._.x (0.js:348:275)<br/>
    at KGa._.x (0.js:348:437)<br/>
    at OGa._.Nc (0.js:353:412)<br/>
    at Ixb._.wh (0.js:1010:14)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Hub_Web/.n/Basic_Editors/.n/Domain/.n/Domain_Selection/app_js/baseJs.js@28)<br/>
Unknown.p5(0.js@332)<br/>
Unknown._.x(0.js@481)<br/>
Unknown._.Q(0.js@409)<br/>
Unknown._.Q(0.js@483)<br/>
Unknown._.Q(0.js@452)<br/>
Unknown._.x(0.js@275)<br/>
Unknown._.x(0.js@437)<br/>
Unknown._.Nc(0.js@412)<br/>
Unknown._.wh(0.js@14)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
