### ISSUE TITLE
Exception 'Maximum call stack size exceeded' when opening Domain Editor

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#206]
For instance, have Micro Page or Micro App object open and then navigate to a Domain object.

Exception reported:

```
Exception reported: (RangeError) : Maximum call stack size exceeded
baseJs.js:88 com.google.gwt.core.client.JavaScriptException: (RangeError) : Maximum call stack size exceeded<br />
RangeError: Maximum call stack size exceeded<br/>
    at a5.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:130:34)<br/>
    at SEa._.P (0.js:1666:123)<br/>
    at Toc._.P (0.js:1447:358)<br/>
    at lvc._._ (0.js:1709:351)<br/>
    at Gu (0.js:1655:88)<br/>
    at pvc._._ (0.js:1710:384)<br/>
    at ls._.P (0.js:1709:230)<br/>
    at mnc._.P (0.js:1396:110)<br/>
    at gsc._.Hb (0.js:1600:254)<br/>
    at Uuc._.Ol (0.js:1693:333)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js@34)<br/>
Unknown._.P(0.js@123)<br/>
Unknown._.P(0.js@358)<br/>
Unknown._._(0.js@351)<br/>
Unknown.Gu(0.js@88)<br/>
Unknown._._(0.js@384)<br/>
Unknown._.P(0.js@230)<br/>
Unknown._.P(0.js@110)<br/>
Unknown._.Hb(0.js@254)<br/>
Unknown._.Ol(0.js@333)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Fixed.
