### ISSUE TITLE
Compilation of ObjectHub Platform Bundle does not work

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#208]
Error reported:

```
Exception reported: (RangeError) : Maximum call stack size exceeded
baseJs.js:88 com.google.gwt.core.client.JavaScriptException: (RangeError) : Maximum call stack size exceeded<br />
RangeError: Maximum call stack size exceeded<br/>
    at Lw._.x (0.js:1665:24)<br/>
    at Iuc._._ (0.js:1687:212)<br/>
    at Gu (0.js:1655:88)<br/>
    at REa._._ (0.js:1665:279)<br/>
    at p5 (0.js:1662:370)<br/>
    at QEa._.x (0.js:1665:389)<br/>
    at Soc._.Q (0.js:1448:409)<br/>
    at Toc._.Q (0.js:1447:483)<br/>
    at pvc._.Q (0.js:1710:452)<br/>
    at pEa._.x (0.js:268:450)<br/>
Unknown._.x(0.js@24)<br/>
Unknown._._(0.js@212)<br/>
Unknown.Gu(0.js@88)<br/>
Unknown._._(0.js@279)<br/>
Unknown.p5(0.js@370)<br/>
Unknown._.x(0.js@389)<br/>
Unknown._.Q(0.js@409)<br/>
Unknown._.Q(0.js@483)<br/>
Unknown._.Q(0.js@452)<br/>
Unknown._.x(0.js@450)<br/>
-end of stack trace
```

**Comment by stellardb** [comment]
Another error reported, happens during `Writing Page` phase

```
Exception reported: (RangeError) : Maximum call stack size exceeded
hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/Objec…Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:88 com.google.gwt.core.client.JavaScriptException: (RangeError) : Maximum call stack size exceeded<br />
RangeError: Maximum call stack size exceeded<br/>
    at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ub_Web/.n/Components/.n/Deployment/.n/Deploy_Panel/app_js/baseJs.js:222:13)<br/>
    at a5.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ub_Web/.n/Components/.n/Deployment/.n/Deploy_Panel/app_js/baseJs.js:202:13)<br/>
    at SEa._.P (0.js:1666:123)<br/>
    at Toc._.P (0.js:1447:358)<br/>
    at lvc._._ (0.js:1709:351)<br/>
    at Gu (0.js:1655:88)<br/>
    at pvc._._ (0.js:1710:384)<br/>
    at ls._.P (0.js:1709:230)<br/>
    at mnc._.P (0.js:1396:110)<br/>
    at gsc._.Hb (0.js:1600:254)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Components/.n/Deployment/.n/Deploy_Panel/app_js/baseJs.js@13)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Components/.n/Deployment/.n/Deploy_Panel/app_js/baseJs.js@13)<br/>
Unknown._.P(0.js@123)<br/>
Unknown._.P(0.js@358)<br/>
Unknown._._(0.js@351)<br/>
Unknown.Gu(0.js@88)<br/>
Unknown._._(0.js@384)<br/>
Unknown._.P(0.js@230)<br/>
Unknown._.P(0.js@110)<br/>
Unknown._.Hb(0.js@254)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Sometimes compilation seems to work as well. Probably some random constellation of what is loaded in the localStorage.

**Comment by mxro** [comment]
The following error happened during the `Writing Bundle ...` stage:

```
Exception reported: (RangeError) : Maximum call stack size exceeded
hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/Objec…Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:88 com.google.gwt.core.client.JavaScriptException: (RangeError) : Maximum call stack size exceeded<br />
RangeError: Maximum call stack size exceeded<br/>
    at a5.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…eb/.n/Basic_Editors/.n/Micro_App/.n/Generate_HTML_Wrapper/baseJs.js:208:27)<br/>
    at SEa._.P (0.js:1666:123)<br/>
    at Toc._.P (0.js:1447:358)<br/>
    at lvc._._ (0.js:1709:351)<br/>
    at Gu (0.js:1655:88)<br/>
    at pvc._._ (0.js:1710:384)<br/>
    at ls._.P (0.js:1709:230)<br/>
    at gsc._.Hb (0.js:1600:254)<br/>
    at Uuc._.Ol (0.js:1693:333)<br/>
    at Uuc.Vuc.Nv.0.2 (0.js:1694:362)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ub_Web/.n/Basic_Editors/.n/Micro_App/.n/Generate_HTML_Wrapper/baseJs.js@27)<br/>
Unknown._.P(0.js@123)<br/>
Unknown._.P(0.js@358)<br/>
Unknown._._(0.js@351)<br/>
Unknown.Gu(0.js@88)<br/>
Unknown._._(0.js@384)<br/>
Unknown._.P(0.js@230)<br/>
Unknown._.Hb(0.js@254)<br/>
Unknown._.Ol(0.js@333)<br/>
Unknown.Vuc.Nv.0.2(0.js@362)<br/>
-end of stack trace
```

**Comment by mxro** [comment]
Fixed.

Problem was loading of the Bundle Micro App - it's JS was compiled in an obsolete way which lead to the error.
