### ISSUE TITLE
Preview does not work - unauthorized exception

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#209]
In a new Micro App (after previously creating a Micro App, previewing it and creating and viewing a test environment for it), go to the preview.

This Micro App is within a collection with a non-ObjectHub user.

The following error occurs:

```
{"errorMessage":"Unauthorized: No secret matching the supplied secret.\n  Secret: [Token.UNSPECIFIED_TOKEN]\n  Node [Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html)]\n  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html), token=Token.UNSPECIFIED_TOKEN]]\n  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]] java.lang.Exception: Unauthorized: No secret matching the supplied secret.\n  Secret: [Token.UNSPECIFIED_TOKEN]\n  Node [Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html)]\n  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html), token=Token.UNSPECIFIED_TOKEN]]\n  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]<br />\nUnknown.at kcc(Unknown Source)<br/>\nUnknown.at Object.qZb(Unknown Source)<br/>\nUnknown.at Object.wZb(Unknown Source)<br/>\nUnknown.at RWe(Unknown Source)<br/>\nUnknown.at RWe(Unknown Source)<br/>\nUnknown.at Object.WWe [as fb](Unknown Source)<br/>\nUnknown.at hXe(Unknown Source)<br/>\nUnknown.at gXe(Unknown Source)<br/>\nUnknown.at PWe(Unknown Source)<br/>\n-end of stack trace","errorType":"Error","stackTrace":["  Secret: [Token.UNSPECIFIED_TOKEN]","  Node [Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html)]","  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html), token=Token.UNSPECIFIED_TOKEN]]","  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]] java.lang.Exception: Unauthorized: No secret matching the supplied secret.","  Secret: [Token.UNSPECIFIED_TOKEN]","  Node [Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html)]","  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mbo/home/my/~*5/.n/Yes_No/preview/html), token=Token.UNSPECIFIED_TOKEN]]","  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]<br />","Unknown.at kcc(Unknown Source)<br/>","Unknown.at Object.qZb(Unknown Source)<br/>","Unknown.at Object.wZb(Unknown Source)<br/>","Unknown.at RWe(Unknown Source)<br/>","Unknown.at RWe(Unknown Source)<br/>","Unknown.at Object.WWe [as fb](Unknown Source)<br/>","Unknown.at hXe(Unknown Source)<br/>","Unknown.at gXe(Unknown Source)<br/>","Unknown.at PWe(Unknown Source)<br/>","-end of stack trace","Object.callback.onFailure (/var/task/index.js:225:100)","cb (/var/task/index.js:236:14)","CYe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:4553:21)","Object.FYe [as x] (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9815:373898)","Object.p_e [as _] (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9815:377696)","RWe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9181:56)","RWe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9181:122)","Object.WWe [as fb] (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9815:372771)","hXe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9215:157)","gXe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:5678:38)"]}
```

**Comment by stellardb** [comment]
This seems to happen when no changes have been made to the Micro App before the preview is opened (eg it has not been compiled).

So open one Micro App and go to the Preview tab, and then create a new Micro App (which will now open on the preview tab) - the error occurs.

**Comment by objecthub-io** [comment]
Somehow this only seems to happen for objects which are created directly in My Objects - eg on the highest level of my objects in the browser.

**Comment by objecthub-io** [comment]
This also only seems to happen on the production system ide and not on ide-dev

**Comment by objecthub-io** [comment]
The error happens in the `Preview App` Micro Service.

The readonlysecret for the node `./preview` is set but for some reason it does not work for `./preview` and './preview/html`. (Even when accessing these node directly via REST)

**Comment by objecthub-io** [comment]
Fixed.

(with a hack that preview cannot be the default page for Micro Apps anymore)

**Comment by objecthub-io** [comment]
This happened again. Create a New Micro App, then go straight to the Preview page:

```
{"errorMessage":"Unauthorized: No secret matching the supplied secret.\n  Secret: [Token.UNSPECIFIED_TOKEN]\n  Node [Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html)]\n  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html), token=Token.UNSPECIFIED_TOKEN]]\n  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]] java.lang.Exception: Unauthorized: No secret matching the supplied secret.\n  Secret: [Token.UNSPECIFIED_TOKEN]\n  Node [Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html)]\n  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html), token=Token.UNSPECIFIED_TOKEN]]\n  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]<br />\nUnknown.at kcc(Unknown Source)<br/>\nUnknown.at Object.qZb(Unknown Source)<br/>\nUnknown.at Object.wZb(Unknown Source)<br/>\nUnknown.at RWe(Unknown Source)<br/>\nUnknown.at RWe(Unknown Source)<br/>\nUnknown.at Object.WWe [as fb](Unknown Source)<br/>\nUnknown.at hXe(Unknown Source)<br/>\nUnknown.at gXe(Unknown Source)<br/>\nUnknown.at PWe(Unknown Source)<br/>\n-end of stack trace","errorType":"Error","stackTrace":["  Secret: [Token.UNSPECIFIED_TOKEN]","  Node [Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html)]","  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html), token=Token.UNSPECIFIED_TOKEN]]","  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]] java.lang.Exception: Unauthorized: No secret matching the supplied secret.","  Secret: [Token.UNSPECIFIED_TOKEN]","  Node [Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html)]","  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mxro2014/home/my/~*2/.n/Test_New_Wrapper/preview/html), token=Token.UNSPECIFIED_TOKEN]]","  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]<br />","Unknown.at kcc(Unknown Source)<br/>","Unknown.at Object.qZb(Unknown Source)<br/>","Unknown.at Object.wZb(Unknown Source)<br/>","Unknown.at RWe(Unknown Source)<br/>","Unknown.at RWe(Unknown Source)<br/>","Unknown.at Object.WWe [as fb](Unknown Source)<br/>","Unknown.at hXe(Unknown Source)<br/>","Unknown.at gXe(Unknown Source)<br/>","Unknown.at PWe(Unknown Source)<br/>","-end of stack trace","Object.callback.onFailure (/var/task/index.js:225:100)","cb (/var/task/index.js:236:14)","CYe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:4553:21)","Object.FYe [as x] (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9815:373898)","Object.p_e [as _] (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9815:377696)","RWe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9181:56)","RWe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9181:122)","Object.WWe [as fb] (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9815:372771)","hXe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:9215:157)","gXe (eval at <anonymous> (/var/task/index.js:21:100), <anonymous>:5678:38)"]
```

**Comment by objecthub-io** [comment]
Fixed.
