### ISSUE TITLE
Triggers cannot be created

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#252]
The following error occurs when creating a new trigger:

```
com.google.gwt.core.client.JavaScriptException: (Error) : A node with an identical address is already defined.
   Address: [./interval]
    Parent: [https://objecthub.io/system-triggers/~*1] java.lang.Exception: A node with an identical address is already defined.
   Address: [./interval]
    Parent: [https://objecthub.io/system-triggers/~*1]<br />
Unknown.at h9b(Unknown Source)<br/>
Unknown.at Object.nWb(Unknown Source)<br/>
Unknown.at Object.tWb(Unknown Source)<br/>
Unknown.at Object._Zd [as db](Unknown Source)<br/>
Unknown.at Object.ry(Unknown Source)<br/>
Unknown.at eSe(Unknown Source)<br/>
Unknown.at Object.fRe [as O](Unknown Source)<br/>
Unknown.at Object.Wve [as O](Unknown Source)<br/>
Unknown.at Object.YYe [as db](Unknown Source)<br/>
-end of stack trace<br />
Error: A node with an identical address is already defined.<br/>
   Address: [./interval]<br/>
    Parent: [https://objecthub.io/system-triggers/~*1] java.lang.Exception: A node with an identical address is already defined.<br/>
   Address: [./interval]<br/>
    Parent: [https://objecthub.io/system-triggers/~*1]<br /><br/>
Unknown.at h9b(Unknown Source)<br/><br/>
Unknown.at Object.nWb(Unknown Source)<br/><br/>
Unknown.at Object.tWb(Unknown Source)<br/><br/>
Unknown.at Object._Zd [as db](Unknown Source)<br/><br/>
Unknown.at Object.ry(Unknown Source)<br/><br/>
Unknown.at eSe(Unknown Source)<br/><br/>
Unknown.at Object.fRe [as O](Unknown Source)<br/><br/>
Unknown.at Object.Wve [as O](Unknown Source)<br/><br/>
Unknown.at Object.YYe [as db](Unknown Source)<br/><br/>
-end of stack trace<br/>
    at Iw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Hub_Web/.n/Basic_Editors/.n/Trigger/.n/Edit_Trigger/app_js/baseJs.js:71:20)<br/>
    at n5 (0.js:1670:332)<br/>
    at XEa._.x (0.js:1673:481)<br/>
    at gpc._.Q (0.js:1458:409)<br/>
    at hpc._.Q (0.js:1457:483)<br/>
    at Avc._.Q (0.js:1718:452)<br/>
    at dHa._.x (0.js:351:275)<br/>
    at RGa._.x (0.js:351:437)<br/>
    at VGa._.Nc (0.js:356:412)<br/>
    at Yxb._.wh (0.js:1018:14)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(Parent@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.at h9b(@-1)<br/>
Unknown.at Object.nWb(@-1)<br/>
Unknown.at Object.tWb(@-1)<br/>
Unknown.at Object._Zd(@-1)<br/>
Unknown.at Object.ry(@-1)<br/>
Unknown.at eSe(@-1)<br/>
Unknown.at Object.fRe(@-1)<br/>
Unknown.at Object.Wve(@-1)<br/>
Unknown.at Object.YYe(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…ectHub_Web/.n/Basic_Editors/.n/Trigger/.n/Edit_Trigger/app_js/baseJs.js@20)<br/>
Unknown.n5(0.js@332)<br/>
Unknown._.x(0.js@481)<br/>
Unknown._.Q(0.js@409)<br/>
Unknown._.Q(0.js@483)<br/>
Unknown._.Q(0.js@452)<br/>
Unknown._.x(0.js@275)<br/>
Unknown._.x(0.js@437)<br/>
Unknown._.Nc(0.js@412)<br/>
Unknown._.wh(0.js@14)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
