### ISSUE TITLE
Error when opening Database Editor for the first Time

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#26]
Error message 

```
Unhandled exception caught by engine: (ReferenceError) : onCaptionClicked is not defined from com.ononedb.nextweb.js.internal.OnedbJsFactory$2@e4ad
0.js:114951 com.google.gwt.core.client.JavaScriptException: (ReferenceError) : onCaptionClicked is not defined<br />
ReferenceError: onCaptionClicked is not defined<br/>
    at Object.app.init (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/List__MA_/app_js/baseJs.js:544:39)<br/>
    at Object.eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:13)<br/>
    at Object.priv.triggerCallback (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:148:21)<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:172:14<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:139:14<br/>
    at callFunction (0.js:132771:3)<br/>
    at Object.apply_661 [as apply_1] (0.js:132875:5)<br/>
    at Object.apply_664 [as apply_1] (0.js:133099:82)<br/>
    at Object.onSuccess_102 [as onSuccess_0] (0.js:118224:78)<br/>
    at Object.onSuccess_101 [as onSuccess_0] (0.js:118164:79)<br/>
Unknown.$collect(JsArrayString.java:42)<br/>
```

**Comment by objecthub-io** [comment]
Doesn't seem to appear anymore.
