### ISSUE TITLE
Reference error onChange not defined on opening JS tab

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#271]
When opening the JS tab of a **Micro Page**, the following error appears sometimes:

```
Exception Message: (ReferenceError) : onChange is not defined

com.google.gwt.core.client.JavaScriptException: (ReferenceError) : onChange is not defined
ReferenceError: onChange is not defined
at Object.app.init (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js:413:36)
at Object.priv.callInit (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:9)
at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:56:19)
at p5 (0.js:1677:332)
at Mtc._.H (0.js:1615:70)
at Voc (0.js:1411:415)
at Woc._.Q (0.js:1412:269)
at Otc._.Ib (0.js:1615:267)
at xwc._.Ql (0.js:1708:333)
at xwc.$v.0.2 (0.js:1709:362)
Unknown.app.init(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js@36)
Unknown.priv.callInit(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@9)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@19)
Unknown.p5(0.js@332)
Unknown._.H(0.js@70)
Unknown.Voc(0.js@415)
Unknown._.Q(0.js@269)
Unknown._.Ib(0.js@267)
Unknown._.Ql(0.js@333)
Unknown.$v.0.2(0.js@362)
-end of stack trace
```

**Comment by objecthub-io** [comment]
This error shows up when opening the JS tab of a Micro Service (or upon opening a Micro Service object)

Esp when navigating from a Micro Page object?

```
Exception Message: (ReferenceError) : compiler is not defined

com.google.gwt.core.client.JavaScriptException: (ReferenceError) : compiler is not defined
ReferenceError: compiler is not defined
at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js:225:37)
at p5 (0.js:1677:332)
at Mtc._.H (0.js:1615:70)
at Voc (0.js:1411:415)
at Woc._.Q (0.js:1412:269)
at Otc._.Ib (0.js:1615:267)
at xwc._.Ql (0.js:1708:333)
at xwc.$v.0.2 (0.js:1709:362)
at X9 (0.js:2435:253)
at S (0.js:2438:393)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js@37)
Unknown.p5(0.js@332)
Unknown._.H(0.js@70)
Unknown.Voc(0.js@415)
Unknown._.Q(0.js@269)
Unknown._.Ib(0.js@267)
Unknown._.Ql(0.js@333)
Unknown.$v.0.2(0.js@362)
Unknown.X9(0.js@253)
Unknown.S(0.js@393)
-end of stack trace
```

**Comment by objecthub-io** [comment]
This only happens in the production version it seems.

**Comment by objecthub-io** [comment]
Fixed.
