### ISSUE TITLE
Error while rendering Micro Pages

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#279]
The following error is displayed when opening a Micro Page:

```
Error: (ReferenceError) : $ is not defined com.google.gwt.core.client.JavaScriptException: (ReferenceError) : $ is not defined
ReferenceError: $ is not defined
at Object.lib.perform (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Prepare_Environment_for_Server_Side_Rendering/baseJs.js:2:16)
at prepareEnvironment (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Render_Page/baseJs.js:27:55)
at Object.embedApp [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Render_Page/baseJs.js:151:17)
at pZe (eval at (/var/task/index.js:25:100), :8486:31)
at Object.APe [as H] (eval at (/var/task/index.js:25:100), :9832:365450)
at ese (eval at (/var/task/index.js:25:100), :8263:70)
at Object.ise [as Q] (eval at (/var/task/index.js:25:100), :9832:322592)
at Object.DPe [as Hb] (eval at (/var/task/index.js:25:100), :9832:365653)
at Object.S0e [as sl] (eval at (/var/task/index.js:25:100), :9832:380861)
at Object.X0e.nBg.0.2 (eval at (/var/task/index.js:25:100), :9745:438)
Unknown.anonymous(Unknown Source)
Unknown.at Object.lib.perform(Unknown Source)
Unknown.at prepareEnvironment(Unknown Source)
Unknown.at Object.embedApp [as b](Unknown Source)
Unknown.at pZe(Unknown Source)
Unknown.at Object.APe [as H](Unknown Source)
Unknown.at ese(Unknown Source)
Unknown.at Object.ise [as Q](Unknown Source)
Unknown.at Object.DPe [as Hb](Unknown Source)
Unknown.at Object.S0e [as sl](Unknown Source)
Unknown.at Object.X0e.nBg.0.2(Unknown Source)
-end of stack trace
Stacktrace:
ReferenceError: $ is not defined

Object.lib.perform (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Prepare_Environment_for_Server_Side_Rendering/baseJs.js:2:16)

prepareEnvironment (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Render_Page/baseJs.js:27:55)

Object.embedApp [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Render_Page/baseJs.js:151:17)

pZe (eval at (/var/task/index.js:25:100), :8486:31)
```

**Comment by objecthub-io** [comment]
Fixed.
