### ISSUE TITLE
Error on Explore Screen when navigating back

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#284]
# Steps

- Search for an object
- Open an object
- Click the back button

# Findings

The following error occurs:

```
Invalid embed. data-embed value must be unique (see Note 00001).
```

```
Exception Message: (TypeError) : Cannot read property 'setObjects' of undefined

com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'setObjects' of undefined
TypeError: Cannot read property 'setObjects' of undefined
at clearObjectDisplay (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Explorer-Main__MA_/app_js/baseJs.js:16:27)
at Pw.showAllObjects [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Explorer-Main__MA_/app_js/baseJs.js:120:5)
at m5 (0.js:1680:332)
at Ztc._.H (0.js:1618:70)
at Rt (0.js:1403:212)
at juc._.w (0.js:1619:368)
at SYb._.H (0.js:1220:303)
at hT (0.js:1464:348)
at Rs (0.js:1464:168)
at Yt (0.js:1197:239)
Unknown.clearObjectDisplay(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Explorer-Main__MA_/app_js/baseJs.js@27)
Unknown.showAllObjects(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Explorer-Main__MA_/app_js/baseJs.js@5)
Unknown.m5(0.js@332)
Unknown._.H(0.js@70)
Unknown.Rt(0.js@212)
Unknown._.w(0.js@368)
Unknown._.H(0.js@303)
Unknown.hT(0.js@348)
Unknown.Rs(0.js@168)
Unknown.Yt(0.js@239)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Another invalid embed message:

![invalid_embed](https://user-images.githubusercontent.com/18300634/29340580-1c120472-8263-11e7-8e06-94f3f88f48d4.PNG)

**Comment by objecthub-io** [comment]
Fixed.
