### ISSUE TITLE
Error when replacing object in object input

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#289]
Sometimes the following error occurs when dropping a new object on an object input.

```
com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Display__MA_", class java.lang.String)].
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Input1", "")]<br />
Error: Cannot remove from parent. Child container was not registered with parent.<br/>
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Display__MA_", class java.lang.String)].<br/>
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Input1", "")]<br/>
    at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:50:13)<br/>
    at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:57:27)<br/>
    at Object.priv.updateObjectDisplay (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Input1/app_js/baseJs.js:13:44)<br/>
    at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Input1/app_js/baseJs.js:137:30)<br/>
    at m5 (0.js:1679:332)<br/>
    at DFa._.x (0.js:1682:482)<br/>
    at Pqc._.Q (0.js:1466:409)<br/>
    at Qqc._.Q (0.js:1465:483)<br/>
    at ixc._.Q (0.js:1727:453)<br/>
    at $Zb._.G (0.js:1232:386)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.lib.unregisterChild(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@13)<br/>
Unknown.lib.unload(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@27)<br/>
Unknown.priv.updateObjectDisplay(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Input1/app_js/baseJs.js@44)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Value_Links/.n/Object_Input1/app_js/baseJs.js@30)<br/>
Unknown.m5(0.js@332)<br/>
Unknown._.x(0.js@482)<br/>
Unknown._.Q(0.js@409)<br/>
Unknown._.Q(0.js@483)<br/>
Unknown._.Q(0.js@453)<br/>
Unknown._.G(0.js@386)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
