### ISSUE TITLE
Cannot reorder nodes in Browser

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#290]
# Steps

- Drag and drop a node from the browser and drop it somewhere on the browser

# Findings

The following error occurs:

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : params.node.uri is not a function
TypeError: params.node.uri is not a function
at Object.priv.performInsert (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js:231:60)
at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js:438:14)
at m5 (0.js:1679:332)
at buc._.H (0.js:1617:70)
at jpc (0.js:1412:415)
at kpc._.Q (0.js:1413:269)
at duc._.Ib (0.js:1617:267)
at Nwc._.Ql (0.js:1710:333)
at Nwc.Owc.$v.0.2 (0.js:1711:362)
at X9 (0.js:2437:253)
Unknown.priv.performInsert(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js@60)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Lists/.n/Drop_Action/.n/List_Drop_Action/baseJs.js@14)
Unknown.m5(0.js@332)
Unknown._.H(0.js@70)
Unknown.jpc(0.js@415)
Unknown._.Q(0.js@269)
Unknown._.Ib(0.js@267)
Unknown._.Ql(0.js@333)
Unknown.Owc.$v.0.2(0.js@362)
Unknown.X9(0.js@253)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
