### ISSUE TITLE
Error 'Maximum call stack size exceeded' when switching to Micro App deploy

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#291]
# Steps

- Open a Micro App and go to the deploy tab
- Open a HTML document
- Go back to the Micro App

# Findings

The following error occurs:

```
Exception Message: (RangeError) : Maximum call stack size exceeded

com.google.gwt.core.client.JavaScriptException: (RangeError) : Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at Object.app.showException (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:94:9)
at UQa.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Header/.n/Header-main/.n/Header_Main__MA_/app_js/baseJs.js:96:36)
at UQa._.ab (0.js:573:459)
at Ru (0.js:1672:88)
at Ru (0.js:1672:107)
at Bwc._.ab (0.js:1704:273)
at Ru (0.js:1672:88)
at UYb._.x (0.js:1220:474)
at Pqc._.P (0.js:1466:269)
at Qqc._.P (0.js:1465:358)
Unknown.app.showException(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js@9)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Header/.n/Header-main/.n/Header_Main__MA_/app_js/baseJs.js@36)
Unknown._.ab(0.js@459)
Unknown.Ru(0.js@88)
Unknown.Ru(0.js@107)
Unknown._.ab(0.js@273)
Unknown.Ru(0.js@88)
Unknown._.x(0.js@474)
Unknown._.P(0.js@269)
Unknown._.P(0.js@358)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Does not seem to appear anymore.
