### ISSUE TITLE
Error on opening deployed MicroApp

### ISSUE THREAD

**Issue by michaelbukachi** [objecthub-io/ObjectHub#293]
Hello. When I deploy a MicroApp I get the following error

```
Error loading app: Cannot convert reported exception result to Java Exception. Exception Result Type: class java.lang.String Exception Result toString: Unauthorized: No secret matching the supplied secret. Secret: [Token.UNSPECIFIED_TOKEN] Node [Nx.reference(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/app_version)] Message: [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/app_version), token=Token.UNSPECIFIED_TOKEN]] Possible identifications of accepted authorizations are [[, master-secret]]

java.lang.Exception: Cannot convert reported exception result to Java Exception. Exception Result Type: class java.lang.String Exception Result toString: Unauthorized: No secret matching the supplied secret. Secret: [Token.UNSPECIFIED_TOKEN] Node [Nx.reference(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/app_version)] Message: [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/app_version), token=Token.UNSPECIFIED_TOKEN]] Possible identifications of accepted authorizations are [[, master-secret]]
Unknown.mM(0.js@113)
Unknown.w(0.js@365)
Unknown.rw(0.js@211)
Unknown._.Ib(0.js@241)
Unknown._.Ql(0.js@333)
Unknown.Rwc.$v.0.2(0.js@362)
Unknown.X9(0.js@245)
Unknown.R(0.js@393)
Unknown.eval(0.js@285)
Unknown.eval(0.js@243)
Unknown.eval(0.js@295)
Unknown.anonymous(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js@12)
Unknown._.x(0.js@24)
Unknown._.ab(0.js@213)
Unknown.jz(0.js@303)
Unknown.jz(0.js@351)
Unknown._.cb(0.js@244)
Unknown.ez(0.js@323)
Unknown.Qu(0.js@68)
Unknown._.P(0.js@449)
Unknown._.P(0.js@358)
Unknown._.cb(0.js@436)
Unknown.jz(0.js@289)
Unknown._.cb(0.js@476)
Unknown._.ci(0.js@271)
Unknown._.G(0.js@210)
Unknown._.G(0.js@190)
Unknown._.fi(0.js@195)
Unknown._.G(0.js@428)
Unknown.$z(0.js@75)
Unknown.Vqc(0.js@460)
Unknown._.G(0.js@441)
Unknown.$z(0.js@75)
Unknown.Vqc(0.js@460)
Unknown.qT(0.js@26)
Unknown.pAc(0.js@377)
Unknown._.Q(0.js@322)
Unknown.QEc(0.js@129)
Unknown._.Q(0.js@118)
Unknown.cHc(0.js@347)
Unknown._.Q(0.js@151)
Unknown.cHc(0.js@347)
Unknown._.Q(0.js@151)
Unknown.cHc(0.js@347)
Unknown._.Q(0.js@151)
Unknown.p5(0.js@116)
Unknown._.Q(0.js@472)
Unknown._.Ih(0.js@230)
Unknown.eval(0.js@131)
Unknown.eval(0.js@243)
Unknown.anonymous(https://objecthub.io/rpc/gwtJsonpRpc/v1?data=7%7C0%7C7%7Chttps%3A%2F%2Fobjecthub.io%2Fjs%2Fv01%2Fstellardb%2F%7CBE20C38815D6357EBA0531CDCB996835%7Cjava.util.ArrayList%2F4159755760%7Cnx.remote.messages.v01.ResolveMessageData%2F1775148088%7Cnx.core.nodes.v01.ReferenceData%2F4285455160%7Chttps%3A%2F%2Fu1.objecthub.io%2Fmahila%2Fhome%2Fmy%2F~*3%2F.n%2FLanding_Page%2Fapp_version%7CToken.UNSPECIFIED_TOKEN%7C1%7C2%7C3%7C1%7C4%7C5%7C6%7C7%7C&callback=__gwt_jsonp__.P0.onSuccess&failureCallback=__gwt_jsonp__.P0.onFailure@18)
-end of stack trace
```

Also, most Embedded micro apps aren't rendered properly.

**Comment by objecthub-io** [comment]
Thank you for reporting this issue.

There was a bug with Micro App deployment. It is fixed now. Just deploy a new version and it should work.

**Comment by michaelbukachi** [comment]
Okay I deployed a new version. The error no longer appears in the browser window. However, when you check Chrome's console there's this error:
```
app_js.value.js:40 Uncaught TypeError: cmpl_load is not a function
    at eval (app_js.value.js:40)
    at eval (baseJs.js:19)
(anonymous) @ app_js.value.js:40
(anonymous) @ baseJs.js:19
setTimeout (async)
lib.cmpl_getSecret @ baseJs.js:17
(anonymous) @ app_js.value.js:17
priv.triggerCallback @ ObjectHub_Core_V3_0.js:333
(anonymous) @ ObjectHub_Core_V3_0.js:357
(anonymous) @ ObjectHub_Core_V3_0.js:324
m5 @ 0.js:1679
_.x @ 0.js:1682
_.Q @ 0.js:1466
_.Q @ 0.js:1465
_.Q @ 0.js:1727
_.Q @ 0.js:1726
gE @ 0.js:1407
_.Q @ 0.js:1407
_.Ib @ 0.js:1617
_.Ql @ 0.js:1710
Rwc.$v.0.2 @ 0.js:1711
X9 @ 0.js:2437
R @ 0.js:2440
(anonymous) @ 0.js:1711
(anonymous) @ 0.js:2442
(anonymous) @ 0.js:1679
(anonymous) @ ObjectHub_Core_V3_0.js:293
(anonymous) @ ObjectHub_Core_V3_0.js:268
init @ Import_Utils.value.js:11
window.Libraries.install @ ObjectHub_Core_V3_0.js:259
priv.requireOne @ ObjectHub_Core_V3_0.js:289
(anonymous) @ ObjectHub_Core_V3_0.js:305
m5 @ 0.js:1679
_.x @ 0.js:1635
_.Q @ 0.js:449
_.Q @ 0.js:1669
_.Q @ 0.js:1465
_.Q @ 0.js:1727
_.ei @ 0.js:1175
_.G @ 0.js:2401
_.G @ 0.js:2369
_.fi @ 0.js:2373
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
qT @ 0.js:1468
_.Q @ 0.js:1213
JG @ 0.js:615
YRa @ 0.js:1444
_.Sd @ 0.js:1442
oT @ 0.js:1212
_.nn @ 0.js:2301
OJc @ 0.js:2293
g9 @ 0.js:2267
N6 @ 0.js:2263
_.om @ 0.js:1918
WNc @ 0.js:2398
_.vn @ 0.js:2400
aS @ 0.js:2355
HS @ 0.js:2360
_.w @ 0.js:1174
_.H @ 0.js:1220
gT @ 0.js:1464
zs @ 0.js:1197
_.w @ 0.js:1170
nsc @ 0.js:1634
lsc @ 0.js:1516
X9 @ 0.js:2437
R @ 0.js:2440
(anonymous) @ 0.js:1508
(anonymous) @ 0.js:2442
window.Apps.priv.performEmbed @ ObjectHub_Core_V3_0.js:619
(anonymous) @ ObjectHub_Core_V3_0.js:646
m5 @ 0.js:1679
_.H @ 0.js:1617
_.w @ 0.js:1615
_.H @ 0.js:1220
gT @ 0.js:1464
Rs @ 0.js:1464
Yt @ 0.js:1197
_.M @ 0.js:1197
Pw @ 0.js:293
$vc @ 0.js:1686
X9 @ 0.js:2437
R @ 0.js:2440
(anonymous) @ 0.js:1685
(anonymous) @ 0.js:2442
(anonymous) @ page&secret=Pb4OkNHB:533
priv.triggerCallback @ ObjectHub_Core_V3_0.js:333
(anonymous) @ ObjectHub_Core_V3_0.js:357
(anonymous) @ ObjectHub_Core_V3_0.js:324
m5 @ 0.js:1679
_.x @ 0.js:1682
_.Q @ 0.js:1466
_.Q @ 0.js:1465
_.Q @ 0.js:1727
_.Q @ 0.js:1726
gE @ 0.js:1407
_.Q @ 0.js:1407
_.Ib @ 0.js:1617
_.Ql @ 0.js:1710
Rwc.$v.0.2 @ 0.js:1711
X9 @ 0.js:2437
R @ 0.js:2440
(anonymous) @ 0.js:1711
(anonymous) @ 0.js:2442
(anonymous) @ 0.js:1679
(anonymous) @ ObjectHub_Core_V3_0.js:293
window.Libraries.install @ ObjectHub_Core_V3_0.js:256
priv.requireOne @ ObjectHub_Core_V3_0.js:289
(anonymous) @ ObjectHub_Core_V3_0.js:305
m5 @ 0.js:1679
_.x @ 0.js:1635
_.Q @ 0.js:449
_.Q @ 0.js:1669
_.Q @ 0.js:1465
_.Q @ 0.js:1727
_.ei @ 0.js:1175
_.G @ 0.js:2401
_.G @ 0.js:2369
_.fi @ 0.js:2373
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
_.G @ 0.js:1468
$z @ 0.js:1419
Vqc @ 0.js:1467
qT @ 0.js:1468
_.Q @ 0.js:1213
JG @ 0.js:615
YRa @ 0.js:1444
_.Sd @ 0.js:1442
oT @ 0.js:1212
_.nn @ 0.js:2301
OJc @ 0.js:2293
g9 @ 0.js:2267
N6 @ 0.js:2263
_.om @ 0.js:1918
WNc @ 0.js:2398
_.vn @ 0.js:2400
aS @ 0.js:2355
HS @ 0.js:2360
_.w @ 0.js:1174
_.H @ 0.js:1220
gT @ 0.js:1464
zs @ 0.js:1197
_.w @ 0.js:1170
nsc @ 0.js:1634
lsc @ 0.js:1516
X9 @ 0.js:2437
R @ 0.js:2440
(anonymous) @ 0.js:1508
(anonymous) @ 0.js:2442
(anonymous) @ ObjectHub_Core_V3_0.js:304
m5 @ 0.js:1679
_.H @ 0.js:1617
Rt @ 0.js:1403
_.w @ 0.js:1618
_.H @ 0.js:1220
gT @ 0.js:1464
Rs @ 0.js:1464
Yt @ 0.js:1197
_.M @ 0.js:1197
Pw @ 0.js:293
$vc @ 0.js:1686
X9 @ 0.js:2437
```
The embedded apps are still not being rendered properly. I'm suspecting it has something to do with the above error.

**Comment by objecthub-io** [comment]
I think you might have an old version of a library in your cache. After opening the deployed app, open the console and type `localStorage.clear();`. (Assure that this happens in the window that has opened the micro app on the domain u1.objecthub.io).

Then reload the page and it should work.

**Comment by michaelbukachi** [comment]
That fixed it. Thanks

**Comment by objecthub-io** [comment]
Hi! Does this issue occur again?

**Comment by michaelbukachi** [comment]
Okay. So the issue is still persistent in a mobile browser  (android)
```
Error loading app: (TypeError) : Object https://u1.objecthub.io/mahila/home/my/~*3/.n/Header has no method 'startsWith'

com.google.gwt.core.client.JavaScriptException: (TypeError) : Object https://u1.objecthub.io/mahila/home/my/~*3/.n/Header has no method 'startsWith'
TypeError: Object https://u1.objecthub.io/mahila/home/my/~*3/.n/Header has no method 'startsWith'
at lib.cmpl_getSecret (eval at (eval at (eval at (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:237:9))), :6:13)
at Object.eval (eval at (eval at (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:237:9)), :17:1)
at Object.priv.triggerCallback (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:333:21)
at https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:357:14
at Object.b (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:324:14)
at m5 (https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS:1679:332)
at Object._.x (https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS:1682:482)
at Object._.Q (https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS:1466:409)
at Object._.Q (https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS:1465:483)
at Object._.Q (https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS:1727:453)
Unknown.cmpl_getSecret(eval at (eval at (eval at (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js@9)
Unknown.eval(eval at (eval at (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js@9)
Unknown.priv.triggerCallback(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js@21)
Unknown.anonymous(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js@14)
Unknown.b(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js@14)
Unknown.m5(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS@332)
Unknown._.x(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS@482)
Unknown._.Q(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS@409)
Unknown._.Q(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS@483)
Unknown._.Q(https://u1.objecthub.io/mahila/home/my/~*3/.n/Landing_Page/deploy/main/versions/~*8/page&secret=8w2ImymS@453)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Hmm, looks like the Android browser does not support [startsWith](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) ...

I have changed it now so that it doesn't use this method anymore. Can you try again? You will need to reload the ObjectHub page and deploy a new version.

**Comment by michaelbukachi** [comment]
Yes it works now. I'll try to check tomorrow if it also works on IOS

**Comment by michaelbukachi** [comment]
Works on IOS.
