### ISSUE TITLE
Error Cannot render variables

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#295]
Sometimes when opening Micro App editor, the following error occurs:

```
Exception reported: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", class java.lang.String)].
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]
hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:90 com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent.
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", class java.lang.String)].
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]<br />
Error: Cannot remove from parent. Child container was not registered with parent.<br/>
  Child app [node("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", class java.lang.String)].<br/>
  Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]<br/>
    at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:50:13)<br/>
    at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:57:27)<br/>
    at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_/app_js/baseJs.js:91:32)<br/>
    at Y4.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Filter_Valid_Variables/baseJs.js:45:9)<br/>
    at FFa._.Q (0.js:1683:230)<br/>
    at Sqc._.Q (0.js:1465:483)<br/>
    at lxc._.Q (0.js:1727:453)<br/>
    at os._.Q (0.js:1726:272)<br/>
    at gE (0.js:1407:317)<br/>
    at Xoc._.Q (0.js:1407:428)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.anonymous(@-1)<br/>
Unknown.lib.unregisterChild(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@13)<br/>
Unknown.lib.unload(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@27)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_/app_js/baseJs.js@32)<br/>
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Filter_Valid_Variables/baseJs.js@9)<br/>
Unknown._.Q(0.js@230)<br/>
Unknown._.Q(0.js@483)<br/>
Unknown._.Q(0.js@453)<br/>
Unknown._.Q(0.js@272)<br/>
Unknown.gE(0.js@317)<br/>
Unknown._.Q(0.js@428)<br/>
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed. Variables list is now rendered in a different way.
