### ISSUE TITLE
Preview for 'App with User Management' cannot be opened

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#296]
# Steps

- Create a new account'
- Fork the [**App with User Management Template**](https://repo.on.objecthub.io/object/template-users)
- Set the correct options in the **Configuration object**
- Open **Frontend / App**
- Open the Preview

# Findings

The following error occurs:

```
{"errorMessage":"Insufficient authorization for accessing preview: No secret matching the supplied secret.\n  Secret: [Token.UNSPECIFIED_TOKEN]\n  Node [Nx.reference(https://u1.objecthub.io/oht20170828/home/my/~*0/it/.n/Frontend/.n/App/preview/html)]\n  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/oht20170828/home/my/~*0/it/.n/Frontend/.n/App/preview/html), token=Token.UNSPECIFIED_TOKEN]]\n  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]","errorType":"Error","stackTrace":["  Secret: [Token.UNSPECIFIED_TOKEN]","  Node [Nx.reference(https://u1.objecthub.io/oht20170828/home/my/~*0/it/.n/Frontend/.n/App/preview/html)]","  Message:  [ResolveMessageData [node=Nx.reference(https://u1.objecthub.io/oht20170828/home/my/~*0/it/.n/Frontend/.n/App/preview/html), token=Token.UNSPECIFIED_TOKEN]]","  Possible identifications of accepted authorizations are [[<unidentified>, master-secret]]","eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Services1/.n/Micro_Apps/.n/Preview_App1/deploy/main/versions/~*1/js/baseJs.js:22:7)","AZe (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:4567:21)","Object.DZe [as x] (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:9832:376020)","Object.t0e [as fb] (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:9832:380097)","PXe (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:9178:31)","PXe (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:9178:122)","Object.UXe [as fb] (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:9832:374893)","fYe (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:9217:157)","eYe (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:5685:38)","NXe (eval at <anonymous> (/var/task/index.js:22:100), <anonymous>:8601:22)"]}
```

**Comment by mxro** [comment]
Fixed. 

Now all /preview nodes are not forked.
