### ISSUE TITLE
Cannot link non-production Micro App to domain

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#304]
The following error occurs:

```
{"errorMessage":"Node does not exist in cache: https://u1.objecthub.io/mahila/home/my/~*3/.n/Contact_Us/app_js. Node serialization cannot be read from cache. Try reloading page. java.lang.Exception: Node does not exist in cache: https://u1.objecthub.io/mahila/home/my/~*3/.n/Contact_Us/app_js. Node serialization cannot be read from cache. Try reloading page.<br />\nUnknown.at bdc(Unknown Source)<br/>\nUnknown.at Object.h$b(Unknown Source)<br/>\nUnknown.at Object.n$b(Unknown Source)<br/>\nUnknown.at Object.z4 [as Q](Unknown Source)<br/>\nUnknown.at Object.g5 [as Q](Unknown Source)<br/>\nUnknown.at Object.vze [as x](Unknown Source)<br/>\nUnknown.at qqe(Unknown Source)<br/>\nUnknown.at Object.tqe [as Q](Unknown Source)<br/>\nUnknown.at Object.tL [as Q](Unknown Source)<br/>\n-end of stack trace","errorType":"Error","stackTrace":["Unknown.at bdc(Unknown Source)<br/>","Unknown.at Object.h$b(Unknown Source)<br/>","Unknown.at Object.n$b(Unknown Source)<br/>","Unknown.at Object.z4 [as Q](Unknown Source)<br/>","Unknown.at Object.g5 [as Q](Unknown Source)<br/>","Unknown.at Object.vze [as x](Unknown Source)<br/>","Unknown.at qqe(Unknown Source)<br/>","Unknown.at Object.tqe [as Q](Unknown Source)<br/>","Unknown.at Object.tL [as Q](Unknown Source)<br/>","-end of stack trace","Object.callback.onFailure (/var/task/index.js:218:100)","cb (/var/task/index.js:229:14)","Object.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Micro_Page/.n/Server_Rendering/.n/Render_Page/baseJs.js:213:13)","tZe (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:3287:23)","Object.PZe [as P] (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:9832:376563)","Object.MBe [as P] (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:9832:338205)","Object.Q2e [as _] (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:9832:383029)","NXe (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:8601:51)","_2e (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:3288:19)","Object.i3e [as _] (eval at <anonymous> (/var/task/index.js:26:100), <anonymous>:9832:383513)"]}
```

**Comment by objecthub-io** [comment]
Fixed.
