### ISSUE TITLE
Error 'Specify parameter target' on linking a path for a domain

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#307]
Trying to add a path to a domain, the following error occurs:

```
Exception Message: (Error) : Specify parameter target.

com.google.gwt.core.client.JavaScriptException: (Error) : Specify parameter target.
Error: Specify parameter target.
at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Domain/.n/Object_Mapping/app_js/baseJs.js:78:24)
at m5 (0.js:1680:332)
at FFa._.x (0.js:1683:482)
at Tqc._.Q (0.js:1467:409)
at Uqc._.Q (0.js:1466:483)
at nxc._.Q (0.js:1728:453)
at NHa._.x (0.js:353:275)
at AHa._.x (0.js:353:437)
at EHa._.Pc (0.js:358:412)
at Azb._.yh (0.js:1025:14)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Basic_Editors/.n/Domain/.n/Object_Mapping/app_js/baseJs.js@24)
Unknown.m5(0.js@332)
Unknown._.x(0.js@482)
Unknown._.Q(0.js@409)
Unknown._.Q(0.js@483)
Unknown._.Q(0.js@453)
Unknown._.x(0.js@275)
Unknown._.x(0.js@437)
Unknown._.Pc(0.js@412)
Unknown._.yh(0.js@14)
-end of stack trace
```

**Comment by mxro** [comment]
Fixed.
