### ISSUE TITLE
Cannot release object - Insufficient authorization for database operation.

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#310]
Upon trying to release an object, the following error occurs:

```
Exception Message: (Error) : Unauthorized: Insufficient authorization for database operation. java.lang.Exception: Unauthorized: Insufficient authorization for database operation.
Unknown.at kcc(Unknown Source)
Unknown.at Object.qZb(Unknown Source)
Unknown.at Object.wZb(Unknown Source)
Unknown.at RWe(Unknown Source)
Unknown.at Object.WWe [as fb](Unknown Source)
Unknown.at hXe(Unknown Source)
Unknown.at gXe(Unknown Source)
Unknown.at PWe(Unknown Source)
Unknown.at Y4d(Unknown Source)
-end of stack trace

com.google.gwt.core.client.JavaScriptException: (Error) : Unauthorized: Insufficient authorization for database operation. java.lang.Exception: Unauthorized: Insufficient authorization for database operation.
Unknown.at kcc(Unknown Source)
Unknown.at Object.qZb(Unknown Source)
Unknown.at Object.wZb(Unknown Source)
Unknown.at RWe(Unknown Source)
Unknown.at Object.WWe [as fb](Unknown Source)
Unknown.at hXe(Unknown Source)
Unknown.at gXe(Unknown Source)
Unknown.at PWe(Unknown Source)
Unknown.at Y4d(Unknown Source)
-end of stack trace
Error: Unauthorized: Insufficient authorization for database operation. java.lang.Exception: Unauthorized: Insufficient authorization for database operation.

Unknown.at kcc(Unknown Source)

Unknown.at Object.qZb(Unknown Source)

Unknown.at Object.wZb(Unknown Source)

Unknown.at RWe(Unknown Source)

Unknown.at Object.WWe [as fb](Unknown Source)

Unknown.at hXe(Unknown Source)

Unknown.at gXe(Unknown Source)

Unknown.at PWe(Unknown Source)

Unknown.at Y4d(Unknown Source)

-end of stack trace
at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/About_and_Manage/.n/Release/.n/Release_Object/baseJs.js:60:20)
at m5 (0.js:1680:332)
at FFa._.x (0.js:1683:482)
at Tqc._.Q (0.js:1467:409)
at Uqc._.Q (0.js:1466:483)
at nxc._.Q (0.js:1728:453)
at NHa._.x (0.js:353:275)
at AHa._.x (0.js:353:437)
at EHa._.Pc (0.js:358:412)
at Azb._.yh (0.js:1025:14)
Unknown.at kcc(@-1)
Unknown.at Object.qZb(@-1)
Unknown.at Object.wZb(@-1)
Unknown.at RWe(@-1)
Unknown.at Object.WWe(@-1)
Unknown.at hXe(@-1)
Unknown.at gXe(@-1)
Unknown.at PWe(@-1)
Unknown.at Y4d(@-1)
Unknown.anonymous(@-1)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/About_and_Manage/.n/Release/.n/Release_Object/baseJs.js@20)
Unknown.m5(0.js@332)
Unknown._.x(0.js@482)
Unknown._.Q(0.js@409)
Unknown._.Q(0.js@483)
Unknown._.Q(0.js@453)
Unknown._.x(0.js@275)
Unknown._.x(0.js@437)
Unknown._.Pc(0.js@412)
Unknown._.yh(0.js@14)
-end of stack trace
```

**Comment by mxro** [comment]
Not a bug. Was caused by trying to release an object that was released on an old repo.
