### ISSUE TITLE
Cannot open class editor

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#316]
When opening a class editor, the following error occurs:

```
Exception Message: (TypeError) : Cannot read property 'name' of undefined

com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
at display (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:103:35)
at Object.res.display (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:172:9)
at Object.app.setDefault (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:97:16)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:203:17)
at initTabLib (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:145:5)
at Object.app.init (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:167:5)
at Object.priv.callInit (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:9)
at Qw.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:56:19)
at m5 (0.js:1680:332)
at guc._.H (0.js:1618:70)
Unknown.display(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js@35)
Unknown.res.display(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js@9)
Unknown.app.setDefault(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js@16)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js@17)
Unknown.initTabLib(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js@5)
Unknown.app.init(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js@5)
Unknown.priv.callInit(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@9)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js@19)
Unknown.m5(0.js@332)
Unknown._.H(0.js@70)
-end of stack trace
```

**Comment by mxro** [comment]
Fixed.
