### ISSUE TITLE
Uploading large files for Files objects lead to error

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#320]
When uploading a large file (e.g. > 3.5 MB) with the [Files object](https://repo.on.objecthub.io/object/files) an error occurs:

```
Exception Message: (Error) : body size is too long

com.google.gwt.core.client.JavaScriptException: (Error) : body size is too long
Error: body size is too long
at Object.success (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Advanced_Editor/.n/Files/.n/Edit_Files/app_js/baseJs.js:31:63)
at i (https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:2:27449)
at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:2:28213)
at y (https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:4:22721)
at XMLHttpRequest.c (https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:4:26925)
Unknown.success(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Advanced_Editor/.n/Files/.n/Edit_Files/app_js/baseJs.js@63)
Unknown.i(https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js@27449)
Unknown.fireWith(https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js@28213)
Unknown.y(https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js@22721)
Unknown.c(https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js@26925)
-end of stack trace
```

**Comment by objecthub-io** [comment]
When uploading a large file (> 8 MB) the following error occurs:

```
Failed to load resource: net::ERR_CONNECTION_RESET

hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Advanced_Editor/.n/Files/.n/Files_Upload.xjs 
```

The following error was reported on the server:

```
Wed Oct 18 23:55:10 EDT 2017 org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 5242880 bytes.
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:70)
Wed Oct 18 23:55:10 EDT 2017   de.mxro.httpserver.netty3.internal.CustomHttpContentCompressor.messageReceived(CustomHttpContentCompressor.java:12)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
Wed Oct 18 23:55:10 EDT 2017   org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
Wed Oct 18 23:55:10 EDT 2017   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Wed Oct 18 23:55:10 EDT 2017   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Wed Oct 18 23:55:10 EDT 2017   java.lang.Thread.run(Thread.java:748)
```

**Comment by objecthub-io** [comment]
Fixed. An error should be shown now.
