### ISSUE TITLE
Error 'Cannot render usage chart.' on ObjectHub load

### ISSUE THREAD

**Issue by stellardb** [objecthub-io/ObjectHub#325]
After loading ObjectHub, the following errors appears:

```
Cannot get usage data. Failure while processing native JavaScript exception: Error: connect ETIMEDOUT 168.235.85.11:443 java.lang.Exception: Failure while processing native JavaScript exception: Error: connect ETIMEDOUT 168.235.85.11:443<br />
Unknown.at kcc(Unknown Source)<br/>
Unknown.at Object.qZb(Unknown Source)<br/>
Unknown.at Object.wZb(Unknown Source)<br/>
Unknown.at Object.l$e [as jl](Unknown Source)<br/>
Unknown.at Object.eval(Unknown Source)<br/>
Unknown.at obc(Unknown Source)<br/>
Unknown.at rbc(Unknown Source)<br/>
Unknown.at Object.eval [as onFailure](Unknown Source)<br/>
Unknown.at ClientRequest.eval(Unknown Source)<br/>
-end of stack trace
```

```
Exception reported: (TypeError) : Cannot read property 'credit' of null
hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:90 com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'credit' of null<br />
TypeError: Cannot read property 'credit' of null<br/>
    at Qw.renderChart [as b] (https://u1.objecthub.io/objecthub/home/my/~*2/data/.n/Instances/.n/UI/.n/Dashboard/.n/Usage_Pie_Chart/.n/Usage_Pie_Chart/app_js/baseJs.js:18:38)<br/>
    at m5 (0.js:1680:332)<br/>
    at guc._.H (0.js:1618:70)<br/>
    at npc (0.js:1413:415)<br/>
    at opc._.Q (0.js:1414:269)<br/>
    at iuc._.Ib (0.js:1618:267)<br/>
    at Swc._.Ql (0.js:1711:333)<br/>
    at Swc.Twc.$v.0.2 (0.js:1712:362)<br/>
    at X9 (0.js:2438:245)<br/>
    at R (0.js:2441:393)<br/>
Unknown.renderChart(https://u1.objecthub.io/objecthub/home/my/~*2/data/.n/Instances/.n/UI/.n/Dashboard/.n/Usage_Pie_Chart/.n/Usage_Pie_Chart/app_js/baseJs.js@38)<br/>
Unknown.m5(0.js@332)<br/>
Unknown._.H(0.js@70)<br/>
Unknown.npc(0.js@415)<br/>
Unknown._.Q(0.js@269)<br/>
Unknown._.Ib(0.js@267)<br/>
Unknown._.Ql(0.js@333)<br/>
Unknown.Twc.$v.0.2(0.js@362)<br/>
Unknown.X9(0.js@245)<br/>
Unknown.R(0.js@393)<br/>
-end of stack trace
```

**Comment by stellardb** [comment]
Fixed.

**Comment by stellardb** [comment]
Wrong issue. Not fixed.

**Comment by objecthub-io** [comment]
Hasn't occurred for a while and now service has changed as well.
