### ISSUE TITLE
Show in Browser sometimes does not work

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#333]
Error shown:

```
Exception Message: (TypeError) : Cannot read property 'name' of undefined

com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
at display (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:103:36)
at Object.res.display (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:172:9)
at Object.app.setDefault (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:93:20)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:203:17)
at initTabLib (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:145:5)
at Object.app.init (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js:167:5)
at Object.priv.callInit (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:9)
at Function.eval [as a] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:56:19)
at L4c (stellardb-0.js:6633:31)
at RZc.SZc [as U] (stellardb-0.js:7641:2652)
at IGc (stellardb-0.js:6371:72)
at JGc.LGc [as bb] (stellardb-0.js:7639:8756)
at TZc.UZc [as zb] (stellardb-0.js:7641:2903)
at u6c.v6c [as perform] (stellardb-0.js:7641:18116)
at eval (stellardb-0.js:4798:40)
at Object.priv.callRender (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:25:10)
at Function.eval [as a] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:54:19)
at L4c (stellardb-0.js:6633:31)
at RZc.SZc [as U] (stellardb-0.js:7641:2652)
at IGc (stellardb-0.js:6371:72)
at GGc (stellardb-0.js:4790:21)
at ZZc.$Zc [as B] (stellardb-0.js:7641:3220)
at Aqc.Bqc [as U] (stellardb-0.js:7637:28882)
at vPc (stellardb-0.js:7263:197)
at ync (stellardb-0.js:2505:19)
at Onc.Fnc [as U] (stellardb-0.js:7637:21037)
at Mm.Nm [as apply] (stellardb-0.js:7633:3845)
at Object.priv.prepareApp (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:58:6)
at Object.eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:104:17)
at Object.priv.triggerCallback (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:333:21)
at https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:357:14
at Function.a (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:324:14)
at L4c (stellardb-0.js:6633:31)
at T4c.U4c [as C] (stellardb-0.js:7641:14598)
at EPc.GPc [as bb] (stellardb-0.js:7640:1205)
at zPc.BPc [as bb] (stellardb-0.js:7640:701)
at N7c (stellardb-0.js:2356:23)
at O7c.X7c [as bb] (stellardb-0.js:7641:21033)
at A7c (stellardb-0.js:2355:23)
at B7c.D7c [as bb] (stellardb-0.js:7641:20232)
at WFc (stellardb-0.js:6688:93)
at XFc.ZFc [as bb] (stellardb-0.js:7639:6676)
at TZc.UZc [as zb] (stellardb-0.js:7641:2903)
at u6c.v6c [as perform] (stellardb-0.js:7641:18116)
at eval (stellardb-0.js:4798:40)
at https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:293:16
at https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js:221:14
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:31:1)
at lib.cmpl_assertLibrary (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Compilation/.n/Import_Utils/baseJs.js:93:13)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:24:3)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Compilation/.n/Import_Utils/baseJs.js:11:13)
Unknown.display(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js)
Unknown.res.display(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js)
Unknown.app.setDefault(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js)
Unknown.initTabLib(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js)
Unknown.app.init(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js/baseJs.js)
Unknown.priv.callInit(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js)
Unknown.L4c(stellardb-0.js)
Unknown.SZc(stellardb-0.js)
Unknown.IGc(stellardb-0.js)
Unknown.LGc(stellardb-0.js)
Unknown.UZc(stellardb-0.js)
Unknown.v6c(stellardb-0.js)
Unknown.eval(stellardb-0.js)
Unknown.priv.callRender(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js)
Unknown.L4c(stellardb-0.js)
Unknown.SZc(stellardb-0.js)
Unknown.IGc(stellardb-0.js)
Unknown.GGc(stellardb-0.js)
Unknown.$Zc(stellardb-0.js)
Unknown.Bqc(stellardb-0.js)
Unknown.vPc(stellardb-0.js)
Unknown.ync(stellardb-0.js)
Unknown.Fnc(stellardb-0.js)
Unknown.Nm(stellardb-0.js)
Unknown.priv.prepareApp(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js)
Unknown.priv.triggerCallback(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js)
Unknown.anonymous(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js)
Unknown.a(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js)
Unknown.L4c(stellardb-0.js)
Unknown.U4c(stellardb-0.js)
Unknown.GPc(stellardb-0.js)
Unknown.BPc(stellardb-0.js)
Unknown.N7c(stellardb-0.js)
Unknown.X7c(stellardb-0.js)
Unknown.A7c(stellardb-0.js)
Unknown.D7c(stellardb-0.js)
Unknown.WFc(stellardb-0.js)
Unknown.ZFc(stellardb-0.js)
Unknown.UZc(stellardb-0.js)
Unknown.v6c(stellardb-0.js)
Unknown.eval(stellardb-0.js)
Unknown.anonymous(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js)
Unknown.anonymous(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/ObjectHub_Core_V3_0.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js)
Unknown.cmpl_assertLibrary(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Compilation/.n/Import_Utils/baseJs.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Compilation/.n/Import_Utils/baseJs.js)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Another error:

```
Exception Message: (TypeError) : editor.getList is not a function

com.google.gwt.core.client.JavaScriptException: (TypeError) : editor.getList is not a function
TypeError: editor.getList is not a function
at Array.onPageChanged (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Browser/.n/Sideboard-My_Objects__MA_/app_js/baseJs.js:103:33)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Navigation/.n/Mini-Browser/.n/MiniNav__MA_/app_js/baseJs.js:141:49)
at Object.callFunction (stellardbdebug-0.js:143638:3)
at Function.apply_1232 (stellardbdebug-0.js:143769:60)
at lambda (stellardbdebug-0.js:687:82)
at JsDataPromise$2.apply_1234 [as apply_2] (stellardbdebug-0.js:143871:85)
at PromiseImpl$3.onSuccess_185 [as onSuccess_1] (stellardbdebug-0.js:128325:79)
at PromiseImpl$1.onSuccess_184 [as onSuccess_1] (stellardbdebug-0.js:128241:80)
at CallbackUtils$9.onSuccess_231 [as onSuccess_1] (stellardbdebug-0.js:146535:82)
at CallbackUtils$4.onSuccess_230 [as onSuccess_1] (stellardbdebug-0.js:146326:82)
at FlowJs$13$1.apply_1207 [as apply_23] (stellardbdebug-0.js:138113:75)
at JsCallback.perform_23 [as perform] (stellardbdebug-0.js:145155:74)
at stellardbdebug-0.js:143657:64
at cb (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Navigation/.n/Browser/.n/Browser__MA_/app_js/baseJs.js:234:17)
at newcb (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Navigation/.n/Browser/.n/Browser__MA_/app_js/baseJs.js:357:9)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Navigation/.n/Browser/.n/Browser__MA_/app_js/baseJs.js:288:21)
at Object.callFunction (stellardbdebug-0.js:143638:3)
at Function.apply_1232 (stellardbdebug-0.js:143769:60)
at lambda (stellardbdebug-0.js:687:82)
at JsDataPromise$2.apply_1234 [as apply_2] (stellardbdebug-0.js:143871:85)
at PromiseImpl$3.onSuccess_185 [as onSuccess_1] (stellardbdebug-0.js:128325:79)
at PromiseImpl$1.onSuccess_184 [as onSuccess_1] (stellardbdebug-0.js:128241:80)
at CallbackUtils$9.onSuccess_231 [as onSuccess_1] (stellardbdebug-0.js:146535:82)
at CallbackUtils$4.onSuccess_230 [as onSuccess_1] (stellardbdebug-0.js:146326:82)
at FlowJs$13$1.apply_1207 [as apply_23] (stellardbdebug-0.js:138113:75)
at JsCallback.perform_23 [as perform] (stellardbdebug-0.js:145155:74)
at stellardbdebug-0.js:143657:64
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:109:14)
at Object.callFunction_0 (stellardbdebug-0.js:143646:3)
at FnJs$2.apply_1233 [as apply_23] (stellardbdebug-0.js:143809:59)
at JsDataPromise$3.onSuccess_221 [as onSuccess_1] (stellardbdebug-0.js:143925:99)
at PromiseImpl$1.onSuccess_184 [as onSuccess_1] (stellardbdebug-0.js:128241:80)
at CallbackUtils$9.onSuccess_231 [as onSuccess_1] (stellardbdebug-0.js:146535:82)
at CallbackUtils$4.onSuccess_230 [as onSuccess_1] (stellardbdebug-0.js:146326:82)
at Object.sequentialInt_1 (stellardbdebug-0.js:120716:70)
at Concurrent$2.onSuccess_161 [as onSuccess_1] (stellardbdebug-0.js:120778:64)
at FlowJs$13$1.apply_1207 [as apply_23] (stellardbdebug-0.js:138113:75)
at JsCallback.perform_23 [as perform] (stellardbdebug-0.js:145155:74)
at stellardbdebug-0.js:143657:64
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:39:14)
at Object.app.init (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Read_Only_View/app_js/baseJs.js:3:2)
at Object.priv.callInit (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:34:9)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:56:19)
at Object.callFunction (stellardbdebug-0.js:143638:3)
at Function.apply_1232 (stellardbdebug-0.js:143769:60)
at lambda (stellardbdebug-0.js:687:82)
at FlowJs$13.apply_1206 [as apply_9] (stellardbdebug-0.js:138065:141)
at Object.sequentialInt_1 (stellardbdebug-0.js:120720:98)
at Concurrent$2.onSuccess_161 [as onSuccess_1] (stellardbdebug-0.js:120778:64)
at FlowJs$13$1.apply_1207 [as apply_23] (stellardbdebug-0.js:138113:75)
at JsCallback.perform_23 [as perform] (stellardbdebug-0.js:145155:74)
at stellardbdebug-0.js:143657:64
at Object.priv.callRender (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:25:10)
at eval (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/App_Initialization.value.js:54:19)
at Object.callFunction (stellardbdebug-0.js:143638:3)
at Function.apply_1232 (stellardbdebug-0.js:143769:60)
at lambda (stellardbdebug-0.js:687:82)
at FlowJs$13.apply_1206 [as apply_9] (stellardbdebug-0.js:138065:141)
at Object.sequentialInt_1 (stellardbdebug-0.js:120720:98)
at Object.sequential_2 (stellardbdebug-0.js:120685:62)
at FlowJs$3.apply_1209 [as apply_0] (stellardbdebug-0.js:138209:59)
at OnedbJsFactory$1.apply_1008 [as apply_9] (stellardbdebug-0.js:105027:83)
at PromiseImpl.requestResult (stellardbdebug-0.js:128161:75)
at PromiseImpl.apply_1172 [as apply_9] (stellardbdebug-0.js:128072:8)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1234(JsDataPromise.java:122)
Unknown.onSuccess_185(PromiseImpl.java:225)
Unknown.onSuccess_184(PromiseImpl.java:142)
Unknown.onSuccess_231(CallbackUtils.java:205)
Unknown.onSuccess_230(CallbackUtils.java:141)
Unknown.apply_1207(FlowJs.java:438)
Unknown.perform_23(JsCallback.java:17)
Unknown.anonymous(FnJs.java:44)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1234(JsDataPromise.java:122)
Unknown.onSuccess_185(PromiseImpl.java:225)
Unknown.onSuccess_184(PromiseImpl.java:142)
Unknown.onSuccess_231(CallbackUtils.java:205)
Unknown.onSuccess_230(CallbackUtils.java:141)
Unknown.apply_1207(FlowJs.java:438)
Unknown.perform_23(JsCallback.java:17)
Unknown.anonymous(FnJs.java:44)
Unknown.callFunction_0(FnJs.java:90)
Unknown.apply_1233(FnJs.java:100)
Unknown.onSuccess_221(JsDataPromise.java:189)
Unknown.onSuccess_184(PromiseImpl.java:142)
Unknown.onSuccess_231(CallbackUtils.java:205)
Unknown.onSuccess_230(CallbackUtils.java:141)
Unknown.sequentialInt_1(Concurrent.java:52)
Unknown.onSuccess_161(Concurrent.java:78)
Unknown.apply_1207(FlowJs.java:438)
Unknown.perform_23(JsCallback.java:17)
Unknown.anonymous(FnJs.java:44)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1206(FlowJs.java:444)
Unknown.sequentialInt_1(Concurrent.java:57)
Unknown.onSuccess_161(Concurrent.java:78)
Unknown.apply_1207(FlowJs.java:438)
Unknown.perform_23(JsCallback.java:17)
Unknown.anonymous(FnJs.java:44)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1206(FlowJs.java:444)
Unknown.sequentialInt_1(Concurrent.java:57)
Unknown.sequential_2(Concurrent.java:34)
Unknown.apply_1209(FlowJs.java:179)
Unknown.apply_1008(OnedbJsFactory.java:44)
Unknown.requestResult(PromiseImpl.java:88)
Unknown.apply_1172(PromiseImpl.java:30)
Unknown.apply_989(DataPromiseImpl.java:44)
Unknown.apply_180(JsDataPromise.java:173)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1234(JsDataPromise.java:134)
Unknown.onSuccess_185(PromiseImpl.java:225)
Unknown.onSuccess_184(PromiseImpl.java:142)
Unknown.onSuccess_231(CallbackUtils.java:205)
Unknown.onSuccess_230(CallbackUtils.java:141)
Unknown.onSuccess_159(CallbackAggregator.java:72)
Unknown.apply_1207(FlowJs.java:438)
Unknown.perform_23(JsCallback.java:17)
Unknown.anonymous(FnJs.java:44)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1219(JH.java:49)
Unknown.apply_1220(JH.java:48)
Unknown.onSuccess_19(CallbackFactory.java:41)
Unknown.onSuccess_219(DataPromiseImpl.java:72)
Unknown.onSuccess_184(PromiseImpl.java:142)
Unknown.onSuccess_231(CallbackUtils.java:205)
Unknown.thenDo_2(OnedbLink.java:114)
Unknown.run_98(LoadAndSynchronizeOperation.java:89)
Unknown.run_84(CallbackSequencer.java:43)
Unknown.process_11(ClientWrapper.java:203)
Unknown.processItems(BetterAccessThreadImplementation.java:131)
Unknown.run_74(BetterAccessThreadImplementation.java:118)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.notifiyFinished(BetterAccessThreadImplementation.java:86)
Unknown.run_74(BetterAccessThreadImplementation.java:122)
Unknown.run_75(BetterAccessThreadImplementation.java:81)
Unknown.run_70(GwtConcurrencyImpl.java:161)
Unknown.execute_15(GwtConcurrencyImpl.java:154)
Unknown.runProtected(BetterAccessThreadImplementation.java:77)
Unknown.startIfRequired(BetterAccessThreadImplementation.java:62)
Unknown.onSuccess_135(SharedCacheFromAsyncMap.java:109)
Unknown.onSuccess_77(StaticCacheMap.java:131)
Unknown.apply_1155(SimpleCachedStore.java:85)
Unknown.onSuccess_152(AsyncCommon.java:370)
Unknown.onSuccess_22(ValueAndContextFilterMap.java:41)
Unknown.onSuccess_218(JsAsyncMap.java:93)
Unknown.onSuccess_217(JsAsyncMap.java:88)
Unknown.onSuccess_224(JsStringValueCallbackWrapper.java:15)
Unknown.anonymous(JsSharedCache.java:323)
Unknown.getJs(JsAsyncMap.java:104)
Unknown.get_108(JsAsyncMap.java:100)
Unknown.get_107(JsAsyncMap.java:74)
Unknown.get_21(ValueAndContextFilterMap.java:31)
Unknown.get_89(PurgeInvalidValuesStore.java:31)
Unknown.get_88(PurgeInvalidValuesStore.java:26)
Unknown.get_80(EnforceAsynchronousPutStoreNew.java:161)
Unknown.get_90(SimpleCachedStore.java:74)
Unknown.get_27(StaticCacheMap.java:117)
Unknown.get_26(StaticCacheMap.java:105)
Unknown.get_85(LazyStartupStore.java:68)
Unknown.get_83(IgnoreKeysStore.java:39)
Unknown.get_63(SharedCacheFromAsyncMap.java:67)
Unknown.scheduleResolve_0(CompressedResolveNodeOperation.java:52)
Unknown.doScheduleResolveFromCacheOrServer(PullExecutor.java:69)
Unknown.tick_1(SynchronizationProcess.java:211)
Unknown.receiveFromClient_0(SynchronizationProcess.java:261)
Unknown.synchronizeProtected(Synchronizer.java:49)
Unknown.synchronize_3(Synchronizer.java:43)
Unknown.synchronize_2(InternalSynchronizedNetwork.java:149)
Unknown.synchronize_0(InternalClient.java:209)
Unknown.andThen(SynchronizeWithCallbackGrammar.java:43)
Unknown.loadNodeAndChildren(LoadAndSynchronizeOperation.java:177)
Unknown.execute_38(LoadAndSynchronizeOperation.java:56)
Unknown.execute_37(LoadAndSynchronizeOperation.java:37)
Unknown.execute_23(GrammarData.java:35)
Unknown.execute_24(NodeGrammarData.java:23)
Unknown.execute_26(NodeGrammarWithCallbackData.java:15)
Unknown.and_14(LoadGrammarAbstract.java:95)
Unknown.apply_964(OnedbLink.java:107)
Unknown.apply_1008(OnedbJsFactory.java:44)
Unknown.requestResult(PromiseImpl.java:88)
Unknown.apply_1172(PromiseImpl.java:30)
Unknown.apply_990(DataPromiseImpl.java:76)
Unknown.apply_963(OnedbLink.java:153)
Unknown.getNode_1(JH.java:44)
Unknown.get_104(JH.java:68)
Unknown.get_94(JsLink.java:221)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1206(FlowJs.java:444)
Unknown.apply_1202(FlowJs.java:106)
Unknown.apply_1008(OnedbJsFactory.java:44)
Unknown.requestResult(PromiseImpl.java:88)
Unknown.get_92(PromiseImpl.java:193)
Unknown.get_61(DataPromiseImpl.java:33)
Unknown.performGet_0(JsDataPromise.java:116)
Unknown.get_8(JsDataPromise.java:84)
Unknown.callFunction(FnJs.java:108)
Unknown.apply_1232(FnJs.java:77)
Unknown.anonymous(Runtime.java:166)
Unknown.apply_1234(JsDataPromise.java:134)
Unknown.onSuccess_185(PromiseImpl.java:225)
Unknown.onSuccess_184(PromiseImpl.java:142)
Unknown.onSuccess_231(CallbackUtils.java:205)
Unknown.onSuccess_230(CallbackUtils.java:141)
Unknown.sequentialInt_1(Concurrent.java:52)
Unknown.run_66(Concurrent.java:86)
Unknown.execute_17(FlowJs.java:187)
Unknown.$executeScheduled(SchedulerImpl.java:50)
Unknown.runScheduledTasks(SchedulerImpl.java:183)
Unknown.flushPostEventPumpCommands(SchedulerImpl.java:347)
Unknown.execute_6(SchedulerImpl.java:78)
Unknown.execute_5(SchedulerImpl.java:141)
Unknown.apply_958(Impl.java:309)
Unknown.entry0(Impl.java:368)
Unknown.anonymous(Impl.java:78)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.
