### ISSUE TITLE
Fix that newly compiled Lambda Service does not work with client Libraries

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#341]
Error reported upon executing Lambda Service:

```
TypeError: Cannot set property 'stackTraceLimit' of undefined
Stacktrace:
Scb (eval at  (/var/task/index.js:22:100), :5846:35)
pcb (eval at  (/var/task/index.js:22:100), :3549:27)
eval (eval at  (/var/task/index.js:22:100), :7786:512482)
Object. (/var/task/index.js:22:95)
Module._compile (module.js:570:32)
Object.Module._extensions..js (module.js:579:10)
Module.load (module.js:487:32)
tryModuleLoad (module.js:446:12)
Function.Module._load (module.js:438:3)
Module.require (module.js:497:17)
require (internal/module.js:20:19)
```

```
START RequestId: 065c2831-0552-11e8-9f23-87dfae47dc2d Version: $LATEST
2018-01-30T00:10:49.639Z	065c2831-0552-11e8-9f23-87dfae47dc2d	(node:1) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
module initialization error: TypeError
    at Xcb (eval at  (/var/task/index.js:22:100), :6992:70)
    at Scb (eval at  (/var/task/index.js:22:100), :5846:35)
    at pcb (eval at  (/var/task/index.js:22:100), :3549:27)
    at eval (eval at  (/var/task/index.js:22:100), :7786:512482)
    at Object. (/var/task/index.js:22:95)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: 065c2831-0552-11e8-9f23-87dfae47dc2d
REPORT RequestId: 065c2831-0552-11e8-9f23-87dfae47dc2d	Duration: 12.53 ms	Billed Duration: 100 ms 	Memory Size: 1536 MB	Max Memory Used: 109 MB	
```

**Comment by mxro** [comment]
Fixed.
