### ISSUE TITLE
Error shown when closing app right after opening it

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#4]
The following error comes up if an app is closed very quickly after opening it:

```
Exception reported: (Error) : Invalid tab. No tab defined for js
app_js.value.js:71 com.google.gwt.core.client.JavaScriptException: (Error) : Invalid tab. No tab defined for js<br />
Error: Invalid tab. No tab defined for js<br/>
    at initTabBtn (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs.value.js:133:19)<br/>
    at Object.res.addTab (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs.value.js:164:9)<br/>
    at Object.app.addTab (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:47:16)<br/>
    at eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:199:21)<br/>
    at Object.eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:152:9)<br/>
    at Object.priv.triggerCallback (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:104:21)<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:128:14<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:95:14<br/>
    at callFunction (0.js:131895:3)<br/>
    at Object.apply_659 [as apply_1] (0.js:131999:5)<br/>
Unknown.$collect(JsArrayString.java:42)<br/>
Unknown.fillInStackTrace_1(StackTraceCreator.java:174)<br/>
Unknown.fillInStackTrace(StackTraceCreator.java:508)<br/>
```

**Comment by mxro** [comment]
Another stack trace

```
/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n…Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:70 Exception reported: (Error) : Invalid tab. No tab defined for html
/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n…Index___Main_Page/.n/Notification/.n/Notification__MA_/app_js/baseJs.js:71 com.google.gwt.core.client.JavaScriptException: (Error) : Invalid tab. No tab defined for html<br />
Error: Invalid tab. No tab defined for html<br/>
    at initTabBtn (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs.value.js:133:19)<br/>
    at Object.res.addTab (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs.value.js:164:9)<br/>
    at Object.app.addTab (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…jectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:47:16)<br/>
    at eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…ectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:199:21)<br/>
    at Object.eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…jectHub_Web/.n/Screens/.n/Object/.n/Object_Tabs__MA_/app_js.value.js:152:9)<br/>
    at Object.priv.triggerCallback (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:148:21)<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:172:14<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:139:14<br/>
    at callFunction (0.js:132771:3)<br/>
    at Object.apply_661 [as apply_1] (0.js:132875:5)<br/>
```

**Comment by objecthub-io** [comment]
Does not seem to appear anymore.
