### ISSUE TITLE
Cannot create object from My Objects page

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#48]
# Steps
- Go to My Objects page
- Create a New Object
# Findings

An error occurs. The object cannot be created.

Error message:

```
read property 'client' of undefined<br />
TypeError: Cannot read property 'client' of undefined<br/>
    at Object.eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~…nents/.n/Lists/.n/Editable_List_From_Database__MA_/app_js/baseJs.js:328:34)<br/>
    at Object.priv.triggerCallback (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:152:21)<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:176:14<br/>
    at https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Core/.n/Libraries.value.js:143:14<br/>
    at callFunction (0.js:134386:3)<br/>
    at Object.apply_692 [as apply_1] (0.js:134490:5)<br/>
    at Object.apply_695 [as apply_1] (0.js:134684:82)<br/>
    at Object.onSuccess_102 [as onSuccess_0] (0.js:119821:78)<br/>
```

**Comment by mxro** [comment]
Fixed.
