### ISSUE TITLE
Error Cannot Display Tab: Cannot Remove from Parent

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#66]
This was encountered when trying to navigate from a library in My Objects to My Objects.

Error reported:

```
Exception Message: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/Code_Editor_Toolbar__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_", "")]

com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/Code_Editor_Toolbar__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_", "")]
Error: Cannot remove from parent. Child container was not registered with parent.
Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/Code_Editor_Toolbar__MA_", "")].
Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_", "")]
at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:41:13)
at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:48:27)
at Object.app.reloadToolbar (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js:32:23)
at finalizeTab (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:47:22)
at Object.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:117:5)
at m5 (0.js:1601:332)
at Object._.J (0.js:1539:271)
```

**Comment by objecthub-io** [comment]
Another exception: 

```
 Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/Code_Editor_Toolbar__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_", "")]

com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/Code_Editor_Toolbar__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_", "")]
Error: Cannot remove from parent. Child container was not registered with parent.
Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/Code_Editor_Toolbar__MA_", "")].
Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_", "")]
at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:49:13)
at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:56:27)
at Object.app.reloadToolbar (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js:33:23)
at finalizeTab (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:47:22)
at Jv.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js:117:5)
at l5 (0.js:1600:332)
at nlc._.J (0.js:1538:271)
at wgc (0.js:1345:230)
at xgc._.P (0.js:1346:154)
at tlc (0.js:1538:415)
at rlc._.zl (0.js:1631:279)
Unknown.anonymous(@-1)
Unknown.anonymous(@-1)
Unknown.lib.unregisterChild(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@13)
Unknown.lib.unload(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@27)
Unknown.app.reloadToolbar(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Code/.n/JavaScript/.n/JavaScript_Editor__MA_/app_js/baseJs.js@23)
Unknown.finalizeTab(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js@22)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Tabs/.n/Tabs/baseJs.js@5)
Unknown.l5(0.js@332)
Unknown._.J(0.js@271)
Unknown.wgc(0.js@230)
Unknown._.P(0.js@154)
Unknown.tlc(0.js@415)
Unknown._.zl(0.js@279)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Fixed.

state.toolbar now set to `null` if editors are unloaded.
