### ISSUE TITLE
Sometimes removing/adding a variable does not work

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#7]
Steps
- Add/Remove a variable in Micro App Editor / Micro Service

Findings

Sometimes there is an error message that the child micro app has already been unloaded (the one for the variable item)

Here the error message

Exception Message: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", "")]. Parent app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]

com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", "")]. Parent app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]
Error: Cannot remove from parent. Child container was not registered with parent.
Child app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_Item__MA_", "")].
Parent app [link("https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_", "")]
at Object.lib.unregisterChild (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:40:13)
at Object.lib.unload (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:47:27)
at eval (https://beta.objecthub.io/dev/~100/~hub/hub/users/main/~objecthub/home/my/~*0/it/.n/ObjectHub_Web/.n/Components/.n/Variables/.n/Variable_List__MA_/app_js.value.js:71:28)
at callFunction (0.js:131895:3)
at Object.apply_659 [as apply_1](0.js:131999:5)

**Comment by objecthub-io** [comment]
Fixed, was problem with attached Hook.
