### ISSUE TITLE
Sometimes Query in Database cannot be Run Again

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#73]
If running a query multiple times in the Database editor, sometimes the following exception occurs and the results are not shown.

```
Exception Message: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_", "")]

com.google.gwt.core.client.JavaScriptException: (Error) : Cannot remove from parent. Child container was not registered with parent. Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_", "")]. Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_", "")]
Error: Cannot remove from parent. Child container was not registered with parent.
Child app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Components/.n/Data/.n/JSON_to_Table__MA_", "")].
Parent app [link("https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_", "")]
at Object.lib.unregisterChild (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:49:13)
at Object.lib.unload (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js:56:27)
at displayResult (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js.value.js:65:29)
at Nv.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js.value.js:58:13)
at m5 (0.js:1601:332)
at yDa._.w (0.js:1604:402)
at Jic._.P (0.js:1401:350)
at Kic._.P (0.js:1400:439)
at Foc._.P (0.js:1649:451)
at MHa._.F (0.js:395:86)
Unknown.anonymous(@-1)
Unknown.anonymous(@-1)
Unknown.lib.unregisterChild(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@13)
Unknown.lib.unload(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Foundation/.n/Micro_Apps/.n/Container.value.js@27)
Unknown.displayResult(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js.value.js@29)
Unknown.eval(https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.n/Import/~*0/.n/ObjectHub_Web/.n/Composition_Editors/.n/Database/.n/Database_Query_Tool__MA_/app_js.value.js@13)
Unknown.m5(0.js@332)
Unknown._.w(0.js@402)
Unknown._.P(0.js@350)
Unknown._.P(0.js@439)
Unknown._.P(0.js@451)
Unknown._.F(0.js@86)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Does not seem to appear anymore.
