### ISSUE TITLE
Deployment does not work if any of the dependencies has non-ascii characters in source code

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#87]
When deploying an object that has any dependencies that has non ascii characters such as '...', deployment will fail with the following message:

```
Exception reported: (InvalidCharacterError) 
 stack: Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Object.priv.uploadService (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Basic_Editors/.n/Micro_Service1/.n/Generate_Service.value.js:230:13)
    at Jv.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Basic_Editors/.n/Micro_Service1/.n/Generate_Service.value.js:287:17)
    at l5 (0.js:1600:332)
    at nlc._.J (0.js:1538:271)
    at wgc (0.js:1345:230)
    at xgc._.P (0.js:1346:154)
    at tlc (0.js:1538:415)
    at rlc._.zl (0.js:1631:279)
    at rlc.Tu.0.2 (0.js:1632:362)
    at Y9 (0.js:2346:227)
 INDEX_SIZE_ERR: 1
 DOMSTRING_SIZE_ERR: 2
 HIERARCHY_REQUEST_ERR: 3
 WRONG_DOCUMENT_ERR: 4
 INVALID_CHARACTER_ERR: 5
 NO_DATA_ALLOWED_ERR: 6
 NO_MODIFICATION_ALLOWED_ERR: 7
 NOT_FOUND_ERR: 8
 NOT_SUPPORTED_ERR: 9
 INUSE_ATTRIBUTE_ERR: 10
 INVALID_STATE_ERR: 11
 SYNTAX_ERR: 12
 INVALID_MODIFICATION_ERR: 13
 NAMESPACE_ERR: 14
 INVALID_ACCESS_ERR: 15
 VALIDATION_ERR: 16
 TYPE_MISMATCH_ERR: 17
 SECURITY_ERR: 18
 NETWORK_ERR: 19
 ABORT_ERR: 20
 URL_MISMATCH_ERR: 21
 QUOTA_EXCEEDED_ERR: 22
 TIMEOUT_ERR: 23
 INVALID_NODE_TYPE_ERR: 24
 DATA_CLONE_ERR: 25
 code: 5: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
com.google.gwt.core.client.JavaScriptException: (InvalidCharacterError) 
 stack: Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Object.priv.uploadService (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Basic_Editors/.n/Micro_Service1/.n/Generate_Service.value.js:230:13)
    at Jv.eval [as b] (https://objecthub.io/hub/users/main/~objecthub/home/my/~*0/it/.n/Platform/.…Web/.n/Basic_Editors/.n/Micro_Service1/.n/Generate_Service.value.js:287:17)
    at l5 (0.js:1600:332)
    at nlc._.J (0.js:1538:271)
    at wgc (0.js:1345:230)
    at xgc._.P (0.js:1346:154)
    at tlc (0.js:1538:415)
    at rlc._.zl (0.js:1631:279)
    at rlc.Tu.0.2 (0.js:1632:362)
    at Y9 (0.js:2346:227)
 INDEX_SIZE_ERR: 1
 DOMSTRING_SIZE_ERR: 2
 HIERARCHY_REQUEST_ERR: 3
 WRONG_DOCUMENT_ERR: 4
 INVALID_CHARACTER_ERR: 5
 NO_DATA_ALLOWED_ERR: 6
 NO_MODIFICATION_ALLOWED_ERR: 7
 NOT_FOUND_ERR: 8
 NOT_SUPPORTED_ERR: 9
 INUSE_ATTRIBUTE_ERR: 10
 INVALID_STATE_ERR: 11
 SYNTAX_ERR: 12
 INVALID_MODIFICATION_ERR: 13
 NAMESPACE_ERR: 14
 INVALID_ACCESS_ERR: 15
 VALIDATION_ERR: 16
 TYPE_MISMATCH_ERR: 17
 SECURITY_ERR: 18
 NETWORK_ERR: 19
 ABORT_ERR: 20
 URL_MISMATCH_ERR: 21
 QUOTA_EXCEEDED_ERR: 22
 TIMEOUT_ERR: 23
 INVALID_NODE_TYPE_ERR: 24
 DATA_CLONE_ERR: 25
```

**Comment by objecthub-io** [comment]
Fixed. Non-Ascii characters show up as '?' for now.
