### ISSUE TITLE
Error upon releasing object 'Node does not have a parent. Node uri: https://objecthub.io'

### ISSUE THREAD

**Issue by objecthub-io** [objecthub-io/ObjectHub#99]
Error reported

```
Exception Message: (Error) : Node does not have a parent. Node uri: https://objecthub.io java.lang.RuntimeException: Node does not have a parent. Node uri: https://objecthub.io
Unknown.at q4b(Unknown Source)
Unknown.at Object.wRb(Unknown Source)
Unknown.at Object.CRb(Unknown Source)
Unknown.at Object.FRb(Unknown Source)
Unknown.at JLd(Unknown Source)
Unknown.at MIe(Unknown Source)
Unknown.at Object.ote [as aj](Unknown Source)
Unknown.at Object.eval(Unknown Source)
Unknown.at u3b(Unknown Source)
-end of stack trace
```

**Comment by objecthub-io** [comment]
Seems to be related to system not being able to determine the user node.

**Comment by objecthub-io** [comment]
Fixed. SystemProperty could not deserilized in JS since it was stored as SerializedNode because of a bug that was fixed long ago.
